apiVersion: apps/v1
kind: Deployment
metadata:
  name: appflowy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appflowy
  template:
    metadata:
      labels:
        app: appflowy
    spec:
      volumes:
        - name: appflowy-volume
          persistentVolumeClaim:
            claimName: appflowy-pvc
      containers:
        - name: appflowy
          image: appflowyio/appflowy_client:main
          volumeMounts:
            - name: appflowy-volume
              mountPath: /home/appflowy
          env:
            - name: DISPLAY
              value: ${DISPLAY}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appflowy-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi