---
kind: Namespace
apiVersion: v1
metadata:
  name: appflowy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appflowy-app
spec:
  replicas: 1 # adjust as needed
  selector:
    matchLabels:
      app: appflowy-app
  template:
    metadata:
      labels:
        app: appflowy-app
    spec:
      containers:
      - name: app
        image: ghcr.io/appflowy/appflowy:0.6.5
        stdinOpen: true
        tty: true
        env:
        - name: DISPLAY
          value: display
        - name: NO_AT_BRIDGE
          value: "1"
        devices:
        - path: /dev/dri
          type: ''
      volumes:
      - name: xauthority
        secret:
          secretName: appflowy-display-secret
      - name: dev-dri
        hostPath:
          path: /dev/dri