apiVersion: apps/v1
kind: Deployment
metadata:
  name: automatic1111
  namespace: ollama
  labels:
    app: automatic1111
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automatic1111
  template:
    metadata:
      labels:
        app: automatic1111
    spec:
      containers:
      - name: automatic1111-container
        image: ghcr.io/ai-dock/stable-diffusion-webui:latest
        ports:
        - containerPort: 1111
        env:
        - name: WEB_ENABLE_AUTH
          value: "false"
        - name: PORT
          value: "1111"
        - name: WEBUI_ARGS
          value: "--api --listen --radio-queue --always-batch-cond-uncond --opt-split-attention --device-id=0"
        volumeMounts:
        - name: models-volume
          mountPath: /opt/stable-diffusion-webui/models
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: automatic1111-models-pvc
      nodeSelector:
        kubernetes.io/hostname: talos-03
---
apiVersion: v1
kind: Service
metadata:
  name: automatic1111-service
  namespace: ollama
spec:
  selector:
    app: automatic1111
  ports:
    - protocol: TCP
      port: 7860  # External port you want to use
      targetPort: 1111  # Port on the pod where Automatic 1111 is listening
  type: LoadBalancer
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: automatic1111-models-pvc
  namespace: ollama
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-nfs-csi"
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi