---
kind: Namespace
apiVersion: v1
metadata:
  name: baikal
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: baikal
  namespace: argocd
spec:
  destination:
    namespace: baikal
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: app-template 
    repoURL: http://bjw-s.github.io/helm-charts/
    targetRevision: 3.3.2
    helm:
      values: |
        controllers:
          main:
            containers:
              main:
                image:
                  repository: docker.io/ckulka/baikal
                  tag: 0.9.5-nginx-php8.2@sha256:89d667ece755bdddfb1ee076c3fd71a72ca165012a113bbcc0601315fe572652
                resources:
                  requests:
                    cpu: 15m
                    memory: 105M
                  limits:
                    memory: 105M
        service:
          main:
            controller: main
            ports:
              http:
                port: 80
        persistence:
          data:
            existingClaim: baikal-data-v1
            globalMounts:
              - path: /var/www/baikal/Specific/
              - path: /var/www/baikal/config/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baikal-data-v1
  namespace: baikal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi