---
kind: Namespace
apiVersion: v1
metadata:
  name: comfyui
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: comfyui
  namespace: argocd
spec:
  destination:
    namespace: comfyui
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: app-template 
    repoURL: http://bjw-s.github.io/helm-charts/
    targetRevision: 3.6.0
    helm:
      values: |
        # install:
        #   remediation:
        #     retries: 3
        # upgrade:
        #   cleanupOnFail: true
        #   remediation:
        #     retries: 3
        #     strategy: rollback
          controllers:
            comfyui:
              annotations:
                reloader.stakater.com/auto: "true"
              containers:
                app:
                  image:
                    repository: ghcr.io/ai-dock/comfyui
                    tag: v2-cuda-12.1.1-base-22.04-v0.2.0@sha256:eacd7b9281383b13b53d86cacc283f856417c79a1312634e8a9cc6308cbe60f6
                  env:
                    TZ: America/New_York
                    PROVISIONING_SCRIPT: "https://raw.githubusercontent.com/ai-dock/comfyui/main/config/provisioning/flux.sh"
                  resources:
                    requests:
                      # nvidia.com/gpu: 1 # requesting 1 GPU
                      cpu: 500m
                      memory: 6Gi
                    limits:
                      memory: 6Gi
                      # nvidia.com/gpu: 1 # requesting 1 GPU
              pod:
                runtimeClassName: nvidia
                nodeSelector:
                  kubernetes.io/hostname: talos-03

          service:
            app:
              controller: comfyui
              ports:
                http:
                  port: 8188
              type: LoadBalancer

          persistence:
            workspace:
              enabled: true
              existingClaim: comfyui-workspace-pvc
              globalMounts:
                - path: /workspace
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: comfyui-workspace-pvc
  namespace: comfyui
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-nfs-csi"
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300G