---
apiVersion: v1
kind: Service
metadata:
  name: comfyui
  labels:
    app: comfyui
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 8188
  selector:
    app: comfyui
---
apiVersion: v1
kind: Pod
metadata:
  name: comfyui
  labels:
    app: comfyui
spec:
  runtimeClassName: nvidia
  containers:
  - name: comfyui
    image: registry.svc.snowgoons.ro/snowgoons/comfyui:2024-07-02
    args: [ "--listen", "0.0.0.0" ]
    imagePullPolicy: Always
    ports:
    - containerPort: 8188
      name: comfyui
      volumeMounts:
      - name: model-folder
        mountPath: /usr/local/ComfyUI/models
    volumes:
    - name: model-folder
      persistentVolumeClaim:
        claimName: comfyui
  nodeSelector:
    kubernetes.io/hostname: talos-lab-02
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui
  namespace: comfyui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi