---
kind: Namespace
apiVersion: v1
metadata:
  name: comfyui
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: comfyui
  namespace: argocd
spec:
  destination:
    namespace: comfyui
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: app-template 
    repoURL: http://bjw-s.github.io/helm-charts/
    targetRevision: 3.6.0
    helm:
      values: |
          controllers:
            comfyui:
              annotations:
                reloader.stakater.com/auto: "true"
              containers:
                app:
                  image:
                    repository: ghcr.io/ai-dock/comfyui
                    tag: v2-cuda-12.1.1-base-22.04-v0.2.0@sha256:eacd7b9281383b13b53d86cacc283f856417c79a1312634e8a9cc6308cbe60f6
                  env:
                    TZ: America/New_York
                    PROVISIONING_SCRIPT: "https://raw.githubusercontent.com/ai-dock/comfyui/main/config/provisioning/default.sh"
                  resources:
                    requests:
                      cpu: 500m
                      memory: 6Gi
                    limits:
                      memory: 6Gi
              pod:
                runtimeClassName: nvidia
                nodeSelector:
                  kubernetes.io/hostname: talos-03

          service:
            app:
              controller: comfyui
              ports:
                http:
                  port: 18188
              

          persistence:
            workspace:
              enabled: true
              existingClaim: comfyui-workspace-pvc
              globalMounts:
                - path: /opt/storage
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: comfyui-workspace-pvc
  namespace: comfyui
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-nfs-csi"
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300G
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: comfyui-ingress
  namespace: comfyui
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: ingress-nginx-internal
  rules:
  - host: comfyui.<path:stringreplacesecret#domain>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: comfyui
            port:
              number: 18188
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: comfyui-http
  namespace: comfyui
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  parentRefs:
  - name: internal
    namespace: gateway
    sectionName: https
  hostnames:
  - "comfyui.<path:stringreplacesecret#domain>"
  rules:
  - backendRefs:
    - name: comfyui
      port: 18188
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: comfyui
  namespace: comfyui
  annotations:
    external-dns.custom/type: private
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  endpoints:
    - dnsName: comfyui.<path:stringreplacesecret#domain>
      recordType: CNAME
      targets:
        - intgw.<path:stringreplacesecret#domain>
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"