---
apiVersion: v1
kind: Service
metadata:
  name: comfyui
  labels:
    app: comfyui
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 8188
  selector:
    app: comfyui
---
apiVersion: v1
kind: Pod
metadata:
  name: comfyui
  labels:
    app: comfyui
spec:
  runtimeClassName: nvidia
  tolerations:
  - key: restriction
    operator: "Equal"
    value: "CUDAonly"
    effect: "NoSchedule"
  containers:
  - name: comfyui
    image: registry.svc.snowgoons.ro/snowgoons/comfyui:2024-07-02
    args: [ "--listen", "0.0.0.0" ]
    imagePullPolicy: Always
    resources:
      limits:
        nvidia.com/gpu: 1
    ports:
    - containerPort: 8188
      name: comfyui
    volumeMounts:
    - mountPath: /usr/local/ComfyUI/models
      name: model-pvc
  volumes:
  - name: model-pvc
    persistentVolumeClaim:
      claimName: comfyui-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
