---
kind: Namespace
apiVersion: v1
metadata:
  name: storage
---
apiVersion: argoproj.io/v1alpha1
kind: Deployment
metadata:
  name: csi-driver-nfs
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-nfs
      version: v4.6.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    externalSnapshotter:
      enabled: false