---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nfs-configsecrets
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: nfs-ip
      remoteRef:
        key: nfs
        property: nfs-ip
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: config-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.235
  share: /mnt/truenas/kubernetes/config
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
  - nconnect=8
  - hard
  - noatime

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: media-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.235
  share: /mnt/truenas/kubernetes/media
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
  - nconnect=8
  - hard
  - noatime
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: media-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.235
  share: /mnt/truenas/kubernetes/media/immich-photos
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
  - nconnect=8
  - hard
  - noatime