---
kind: Namespace
apiVersion: v1
metadata:
  name: storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-driver-nfs
  namespace: storage
spec:
  containers:
  - name: csi-driver-nfs
    image: ghcr.io/kubernetes-csi/csi-driver-nfs.git:4.6.0
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    externalSnapshotter:
      enabled: false