---
kind: Namespace
apiVersion: v1
metadata:
  name: test
---
apiVersion: argoproj.io/v1alpha1
kind: Deployment
metadata:
  name: csi-driver-nfs
  namespace: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-drivers-nfs
  template:
    metadata: 
      labels:
        app: csi-driver-nfs
    spec:
      containers: 
      - name: csi-driver-nfs
        image: ghcr.io/kubernetes-csi/csi-driver-nfs
        version: v4.6.0
    install:
      createNamespace: true
      remediation:
        retries: 5
    upgrade:
      remediation:
        retries: 5
    values:
      externalSnapshotter:
        enabled: false