
---
kind: Namespace
apiVersion: v1
metadata:
  name: democratic-csi
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-configsecrets
  namespace: democratic-csi
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DEMOCRATIC_VAR_NFS_IP: "{{ .nfs_ip }}"
        DEMOCRATIC_VAR_TRUENAS_RSA: "{{ .rsa }}"
        DEMOCRATIC_VAR_USERNAME: "{{ .username }}"
        DEMOCRATIC_VAR_PASSWORD: "{{ .password }}"
        DEMOCRATIC_VAR_TRUENAS_API: "{{ .api_key }}"
  data:
    - secretKey: nfs_ip
      remoteRef:
        key: nfs
        property: truenas_ip
    - secretKey: rsa
      remoteRef:
        key: nfs
        property: truenas_rsa
    - secretKey: username
      remoteRef:
        key: nfs
        property: username
    - secretKey: api_key
      remoteRef:
        key: nfs
        property: truenas_api_key
    - secretKey: password
      remoteRef:
        key: nfs
        property: password_truenas
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zfs-nfs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://democratic-csi.github.io/charts/
    targetRevision: "0.14.6"
    chart: democratic-csi
    helm:
      values: |
          csiDriver:
            name: "nfs"
          storageClasses:
          - name: nfs
            defaultClass: false
            reclaimPolicy: Delete
            volumeBindingMode: Immediate
            allowVolumeExpansion: true
            parameters:
              fsType: nfs        
          mountOptions:
          - noatime
          - nfsvers=3
          secrets:
            provisioner-secret:
            controller-publish-secret:
            node-stage-secret:
            node-publish-secret:
            controller-expand-secret:
          volumeSnapshotClasses:
          - name: nfs
            parameters:
              detachedSnapshots: "true"
          driver:
            config:
              driver: freenas-api-nfs
              instance_id:
              httpConnection:
                protocol: http
                host: 192.168.1.235
                port: 80
                apiKey: "{{ .api_key }}"
                allowInsecure: true
              zfs:
                # Make sure to use the storage pool that was created previously
                datasetParentName: truenas/kubernetes/nfs/vols
                detachedSnapshotsDatasetParentName: truenas/kubernetes/nfs/snaps
                datasetEnableQuotas: true
                datasetEnableReservation: false
                datasetPermissionsMode: "0777"
                datasetPermissionsUser: 0
                datasetPermissionsGroup: 0
              nfs:
                shareHost: 192.168.1.235
                shareAlldirs: false
                shareAllowedHosts: []
                shareAllowedNetworks: []
                shareMaprootUser: root
                shareMaprootGroup: root
                shareMapallUser: ""
                shareMapallGroup: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: democratic-csi
