---
kind: Namespace
apiVersion: v1
metadata:
  name: external-dns-pihole
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-pihole
  namespace: external-dns-pihole
spec:
  destination:
    namespace: external-dns-pihole
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: external-dns
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 7.2.0
    helm:
      valuesObject:
        fullnameOverride: external-dns-pihole
        policy: upsert-only
        registry: noop
        txtSuffix: .external-dns-pihole
        txtOwnerId: kubernetes
        crd:
          create: true
        sources:
          - service
          - ingress
          # - crd
        provider: pihole
        pihole:
          server: "http://192.168.1.165"
        annotationFilter: "external-dns.custom/type in (private)"
        podSecurityContext.fsGroup: 65534
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true