---
kind: Namespace
apiVersion: v1
metadata:
  name: external-dns-unifi
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-unifi
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
  cluster:
    name: talos-proxmox-cluster
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.0.0
    helm:
      values: |
        {{ .Values }}
      extraArgs:
      policy: sync
      txtOwnerId: default
      txtPrefix: k8s.
      domainFilters: ["marcthespot.com"]
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-dns-values
data:
  provider.json: |
    {"type": "webhook", "config": {"image": {"repository": "ghcr.io/kashalls/external-dns-unifi-webhook", "tag": "0.2.0"}, "env": [{"name": "UNIFI_HOST", "value": "https://192.168.1.1"}, {"name": "UNIFI_USER", "value": "externaldns"}, {"name": "UNIFI_PASS", "value": "Externaldns123"}, {"name": "LOG_LEVEL", "value": "debug"}], "livenessProbe": {"httpGet": {"path": "/healthz", "port": "http-wh-metrics"}, "initialDelaySeconds": 10, "timeoutSeconds": 5}, "readinessProbe": {"httpGet": {"path": "/readyz", "port": "http-wh-metrics"}, "initialDelaySeconds": 10, "timeoutSeconds": 5}}