---
kind: Namespace
apiVersion: v1
metadata:
  name: external-dns-unifi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: bitnami/external-dns:8.0.0
        env:
        - name: LOG_LEVEL
          value: debug
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-pihole
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    namespace: external-dns-pihole
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: external-dns
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 7.3.0
    helm:
      values: |
        annotationFilter: "external-dns.custom/type in (private)"
        provider:
          webhook:
            image:
              repository: ghcr.io/kashalls/external-dns-unifi-webhook
              tag: 0.2.0
            env:
              - name: UNIFI_HOST
                value: https://192.168.1.1 
              - name: UNIFI_USER
                value: externaldns
              - name: UNIFI_PASS
                value: Externaldns123
              - name: LOG_LEVEL
                value: debug
            livenessProbe:
              httpGet:
                path: /healthz
                port: http-wh-metrics
              initialDelaySeconds: 10
              timeoutSeconds: 5
            readinessProbe:
              httpGet:
                path: /readyz
                port: http-wh-metrics
              initialDelaySeconds: 10
              timeoutSeconds: 5
