---

kind: Namespace
apiVersion: v1
metadata:
  name: external-dns-unifi
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-unifi
  namespace: external-dns-unifi
  labels:
    app.kubernetes.io/part-of: external-dns-unifi
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        EXTERNAL_DNS_UNIFI_USER: "{{ .unifi_user }}"
        EXTERNAL_DNS_UNIFI_PASS: "{{ .unifi_pass }}"
  data:
    - secretKey: unifi_user
      remoteRef:
        key: external-dns-unifi
        property: UNIFI_USER
    - secretKey: unifi_pass
      remoteRef:
        key: external-dns-unifi
        property: UNIFI_PASS
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-unifi
spec:
  destination:
    namespace: external-dns-unifi
  project: default
  sources:
  - git:
      repoURL: https://github.com/kubernetes-sigs/external-dns.git
      revision: main
  target:
    server: https://kubernetes.default.svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns-unifi
  template:
    metadata:
      labels:
        app: external-dns-unifi
    spec:
      containers:
      - name: external-dns
        image: ghcr.io/kashalls/external-dns-unifi-webhook:main
        env:
          - name: UNIFI_HOST
            value: https://192.168.1.1
          - name: UNIFI_USER
            value: "{{ .unifi_user }}"
          - name: UNIFI_PASS
            value: "{{ .unifi_pass }}"
          - name: LOG_LEVEL
            value: debug
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-wh-metrics
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-wh-metrics
          initialDelaySeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-dns-unifi-config
data:
  log-level: "debug"
  provider-webhook-image: "ghcr.io/kashalls/external-dns-unifi-webhook:main"

