---

kind: Namespace
apiVersion: v1
metadata:
  name: external-dns-unifi
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-unifi
  namespace: external-dns-unifi
  labels:
    app.kubernetes.io/part-of: external-dns-unifi
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        EXTERNAL_DNS_UNIFI_USER: "{{ .unifi_user }}"
        EXTERNAL_DNS_UNIFI_PASS: "{{ .unifi_pass }}"
  data:
    - secretKey: unifi_user
      remoteRef:
        key: external-dns-unifi
        property: UNIFI_USER
    - secretKey: unifi_pass
      remoteRef:
        key: external-dns-unifi
        property: UNIFI_PASS
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-unifi
spec:
  destination:
    namespace: external-dns-unifi
  source:
    git:
      repoURL: 'https://github.com/marcthespot0/home-lab.git'
      path: manifest/external-dns-unifi.yaml
      targetRevision: HEAD
  project: home-lab
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-dns-unifi-webhook
  namespace: external-dns-unifi
data:
  values.yaml: |
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/kashalls/external-dns-unifi-webhook
          tag: v0.2.0@sha256:4f0d996ba6932f38e921b0717ba44cb58b7d687dcf6a55c9d3843396d23b22d1
        env:
          - name: UNIFI_HOST
            value: https://192.168.1.1
          - name: UNIFI_USER
            valueFrom:
              secretKeyRef:
                key: EXTERNAL_DNS_UNIFI_USER
                name: external-dns-unifi-secret
          - name: UNIFI_PASS
            valueFrom:
              secretKeyRef:
                key: EXTERNAL_DNS_UNIFI_PASS
                name: external-dns-unifi-secret
