---
kind: Namespace
apiVersion: v1
metadata:
  name: external-dns-unifi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns-unifi
  template:
    metadata:
      labels:
        app: external-dns-unifi
    spec:
      containers:
      - name: external-dns-unifi
        image: ghcr.io/kashalls/external-dns-unifi-webhook:v0.2.0@sha256:4f0d996ba6932f38e921b0717ba44cb58b7d687dcf6a55c9d3843396d23b22d1
        env:
        - name: UNIFI_HOST
          value: https://192.168.1.1
        - name: UNIFI_USER
          value: externaldns
        - name: UNIFI_PASS
          value: Externaldns123
        - name: LOG_LEVEL
          value: debug
        ports:
        - containerPort: 80

      livenessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 10
        timeoutSeconds: 5

      readinessProbe:
        httpGet:
          path: /readyz
          port: 80
        initialDelaySeconds: 10
        timeoutSeconds: 5