---
kind: Namespace
apiVersion: v1
metadata:
  name: external-dns-pihole
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-pihole
  namespace: argocd
spec:
  destination:
    namespace: external-dns-pihole
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: external-dns
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 7.2.0
    helm:
      valuesObject:
        fullnameOverride: external-dns-pihole
        policy: sync
        txtSuffix: .external-dns-pihole
        txtOwnerId: kubernetes
        crd:
          create: true
        sources:
          - service
          - ingress
          - crd
        provider: pihole
        pihole.server: "10.96.220.73"
        annotationFilter: "external-dns.custom/type in (private)"
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
