---
kind: Namespace
apiVersion: v1
metadata:
  name: external-dns-pihole
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: external-dns
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 7.2.0
    helm:
      valuesObject:
        fullnameOverride: external-dns
        policy: sync
        txtSuffix: .external-dns
        txtOwnerId: kubernetes
        crd:
          create: true
        sources:
          - service
          - ingress
          - crd
        provider: cloudflare
        cloudflare:
          secretName: external-dns
        annotationFilter: "external-dns.custom/type in (public)"
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
