---
kind: Namespace
apiVersion: v1
metadata:
  name: external-dns-unifi
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-unifi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    namespace: external-dns-unifi
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: external-dns
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.0.0
    helm:
      values: |
        fullnameOverride: external-dns-unifi
        provider:
          name: webhook
          webhook:
            image:
              repository: ghcr.io/kashalls/external-dns-unifi-webhook
              tag: v0.2.0@sha256:4f0d996ba6932f38e921b0717ba44cb58b7d687dcf6a55c9d3843396d23b22d1
            env:
              - name: UNIFI_HOST
                value: https://192.168.1.1 
              - name: UNIFI_USER
                value: externaldns
              - name: UNIFI_PASS
                value: Externaldns123
              - name: LOG_LEVEL
                value: debug
            livenessProbe:
              httpGet:
                path: /healthz
                port: http-wh-metrics
              initialDelaySeconds: 10
              timeoutSeconds: 5
            readinessProbe:
              httpGet:
                path: /readyz
                port: http-wh-metrics
              initialDelaySeconds: 10
              timeoutSeconds: 5
      extraArgs:
      policy: sync
      txtOwnerId: default
      txtPrefix: k8s.
      domainFilters: ["marcthespot.com"]
      annotations:
        external-dns.custom/type: "private"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true