---
kind: Namespace
apiVersion: v1
metadata:
  name: external-dns-unifi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: bitnami/external-dns:8.0.0
        env:
        - name: LOG_LEVEL
          value: debug
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-unifi
spec:
  destination:
    namespace: flux-system
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      chart:
        repository: https://charts.bitnami.com/bitnami
        name: external-dns
        version: 8.0.0
      values:
        fullnameOverride: "external-dns-unifi"
        provider:
          name: webhook
          webhook:
            image:
              repository: ghcr.io/kashalls/external-dns-unifi-webhook
              tag: v0.2.0@sha256:4f0d996ba6932f38e921b0717ba44cb58b7d687dcf6a55c9d3843396d23b22d1
            env:
              - name: UNIFI_HOST
                value: "https://192.168.1.1"
              - name: UNIFI_USER
                value: externaldns
              - name: UNIFI_PASS
                value: Externaldns123
            livenessProbe:
              httpGet:
                path: "/healthz"
                port: "http-wh-metrics"
              initialDelaySeconds: 10
              timeoutSeconds: 5
            readinessProbe:
              httpGet:
                path: "/readyz"
                port: "http-wh-metrics"
              initialDelaySeconds: 10
              timeoutSeconds: 5
        extraArgs:
          - --ignore-ingress-tls-spec
        txtOwnerId: default
        txtPrefix: k8s.
        domainFilters: ["marcthespot.com"] 
    syncPolicy:
      automated:
        prune: true
  targets:
  - namespace: external-dns-unifi
