---

kind: Namespace
apiVersion: v1
metadata:
  name: external-dns-unifi
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-unifi
  namespace: external-dns-unifi
  labels:
    app.kubernetes.io/part-of: external-dns-unifi
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        EXTERNAL_DNS_UNIFI_USER: "{{ .unifi_user }}"
        EXTERNAL_DNS_UNIFI_PASS: "{{ .unifi_pass }}"
  data:
    - secretKey: unifi_user
      remoteRef:
        key: external-dns-unifi
        property: UNIFI_USER
    - secretKey: unifi_pass
      remoteRef:
        key: external-dns-unifi
        property: UNIFI_PASS
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-unifi
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: my-project
  source:
    repoURL: 'https://github.com/your-username/external-dns-charts.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
  resources:
  - name: external-dns-unifi
    namespace: default
    helm:
      valueFiles:
        - values.yaml
      releaseName: external-dns-unifi
      chart:
        repository: https://kubernetes-charts.storage.googleapis.com/
        name: external-dns
        version: 1.14.5
      interval: 12h
      maxHistory: 3
      cleanupOnFail: true
      keepHistory: false
      provider:
        webhook:
          image:
            repository: ghcr.io/kashalls/external-dns-unifi-webhook
            tag: v0.2.0
          env:
            - name: UNIFI_HOST
              value: https://192.168.1.1
            - name: UNIFI_USER
              value: external-dns
            - name: UNIFI_PASS
              valueFrom:
                secretKeyRef:
                  name: external-dns-unifi
                  key: external_dns_unifi
          livenessProbe:
            httpGet:
              path: /healthz
              port: http-wh-metrics
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: http-wh-metrics
            initialDelaySeconds: 10
            timeoutSeconds: 5
      resources:
        requests:
          cpu: 16m
          memory: 90M
        limits:
          memory: 90M
      serviceMonitor:
        enabled: true
      sources:
        - gateway-httproute
      txtPrefix: k8s.
      txtOwnerId: home-cluster
