---
kind: Namespace
apiVersion: v1
metadata:
  name: glance
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glance
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    chart: app-template
    repoURL: https://bjw-s-labs.github.io/helm-charts
    targetRevision: 4.1.1
    helm:
      values: |
        controllers:
          glance:
            strategy: RollingUpdate
            annotations:
              reloader.stakater.com/auto: "true"
            containers:
              glance:
                image:
                  repository: glanceapp/glance
                  tag: v0.8.4@sha256:6df86a7e8868d1eda21f35205134b1962c422957e42a0c44d4717c8e8f741b1a
                args:
                  - --config
                  - /config/glance.yaml
                env:
                  TZ: "${TIMEZONE}"
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities: { drop: ["ALL"] }
        service:
          app:
            controller: glance
            type: ClusterIP
            ports:
              http:
                port: 8080
        persistence:
           config:
             enabled: true
             type: configMap
             name: glance-configmap
           data:
            enabled: true
            existingClaim: glance
            advancedMounts:
              glance:
                app:
                  - path: /config/glance.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: glance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-configmap
  namespace: glance
  labels:
    app.kubernetes.io/name: glance
data:
  glance.yaml: |
      pages:
        - name: Start
          width: slim
          hide-desktop-navigation: true
          center-vertically: true
          columns:
            - size: full
              widgets:
                - type: search
                  autofocus: true
      
                - type: monitor
                  cache: 1m
                  title: Services
                  sites:
                    - title: Plex
                      url: https://plex.marcthespot.com
                      icon: si:plex
                    - title: Radarr
                      url: https://radarr.marcthespot.com/
                      icon: si:radarr
                    - title: Sonarr
                      url: https://Sonarr.marcthespot.com/
                      icon: si:sonarr      
                    - title: Transmission
                      url: https://transmission.marcthespot.com
                      title: Transmission
                    - title: Homeassistant
                      url: http://192.168.1.210:8123
                      icon: si:homeassistant
                    - title: Truenas
                      url: http://192.168.1.235
                      icon: si:truenas
                    
                      
               - type: bookmarks
                  groups:
                    - title: General
                      links:
                        - title: Gmail
                          url: https://mail.google.com/mail/u/0/
                        - title: Amazon
                          url: https://www.amazon.com/
                        - title: Github
                          url: https://github.com/
                    - title: Entertainment
                      links:
                        - title: YouTube
                          url: https://youtube.com/
                        - title: Netflix
                          url: https://netflix.com/
                    - title: Social
                      links:
                        - title: Reddit
                          url: https://reddit.com/
                        - title: X
                          url: https://x.com/
                        - title: Facebook
                          url: https://facebook.com
                        - title: Instagram
                          url: https://instagram.com
        - name: Markets
          columns:
            - size: small
              widgets:
                - type: markets
                  title: Indices
                  markets:
                    - symbol: SPY
                      name: S&P 500
                    - symbol: DX-Y.NYB
                      name: Dollar Index
                - type: markets
                  title: Stocks
                  sort-by: absolute-change
                  markets:
                    - symbol: NVDA
                      name: NVIDIA
                    - symbol: AAPL
                      name: Apple
                    - symbol: MSFT
                      name: Microsoft
                    - symbol: GOOGL
                      name: Google
                    - symbol: AMD
                      name: AMD
                    - symbol: RDDT
                      name: Reddit
                    - symbol: AMZN
                      name: Amazon
                    - symbol: TSLA
                      name: Tesla
                    - symbol: INTC
                      name: Intel
                    - symbol: META
                      name: Meta
            - size: full
              widgets:
                - type: rss
                  title: News
                  style: horizontal-cards
                  feeds:
                    - url: https://feeds.bloomberg.com/markets/news.rss
                      title: Bloomberg
                    - url: https://moxie.foxbusiness.com/google-publisher/markets.xml
                      title: Fox Business
                    - url: https://moxie.foxbusiness.com/google-publisher/technology.xml
                      title: Fox Business
                - type: group
                  widgets:
                    - type: reddit
                      show-thumbnails: true
                      subreddit: technology
                    - type: reddit
                      show-thumbnails: true
                      subreddit: wallstreetbets
                - type: videos
                  style: grid-cards
                  collapse-after-rows: 3
                  channels:
                    - UCvSXMi2LebwJEM1s4bz5IBA # New Money
                    - UCV6KDgJskWaEckne5aPA0aQ # Graham Stephan
                    - UCAzhpt9DmG6PnHXjmJTvRGQ # Federal Reserve
            - size: small
              widgets:
                - type: rss
                  title: News
                  limit: 30
                  collapse-after: 13
                  feeds:
                    - url: https://www.ft.com/technology?format=rss
                      title: Financial Times
                    - url: https://feeds.a.dj.com/rss/RSSMarketsMain.xml
                      title: Wall Street Journal
      
        - name: Gaming
          columns:
            - size: small
              widgets:
                - type: twitch-top-games
                  limit: 20
                  collapse-after: 10
                  exclude:
                    - just-chatting
                    - pools-hot-tubs-and-beaches
                    - music
                    - art
                    - asmr
                - type: twitch-channels
                  channels:
                    - gamesdonequick
                    - teammacintyre
                    - nilaus
                    - nefrums
                    - raxxanterax
            - size: full
              widgets:
                - type: group
                  widgets:
                    - type: reddit
                      show-thumbnails: true
                      subreddit: pcgaming
                    - type: reddit
                      subreddit: games
      
                - type: videos
                  style: grid-cards
                  collapse-after-rows: 3
                  channels:
                    - UCNvzD7Z-g64bPXxGzaQaa4g # gameranx
                    - UCZ7AeeVbyslLM_8-nVy2B8Q # Skill Up
                    - UCHDxYLv8iovIbhrfl16CNyg # GameLinked
                    - UC9PBzalIcEQCsiIkq36PyUA # Digital Foundry
      
            - size: small
              widgets:
                - type: reddit
                  subreddit: gamingnews
                  limit: 7
                  style: vertical-cards
      
        - name: Home
          columns:
            - size: small
              widgets:
                - type: calendar
      
                - type: rss
                  limit: 10
                  collapse-after: 3
                  cache: 10m
                  feeds:
                    - url: http://feeds.macrumors.com/MacRumors-All
                      title: MacRumors
                    - url: https://www.phoronix.com/rss.php
                      title: Phoronix
                    - url: https://www.gamingonlinux.com/article_rss.php
                    - url: https://chipsandcheese.com/feed/
                    - url: https://www.home-assistant.io/atom.xml
      
                - type: twitch-channels
                  channels:
                    - gamesdonequick
                    - teammacintyre
                    - nilaus
                    - nefrums
                    - raxxanterax
      
            - size: full
              widgets:
                - type: hacker-news
      
                - type: videos
                  channels:
                    - UChIs72whgZI9w6d6FhwGGHA # Gamers Nexus
                    - UC4w1YQAJMWOz4qtxinq55LQ # Level1Techs
                    - UCI8iQa1hv7oV_Z8D35vVuSg # Hardware Unboxed
                    - UCv6J_jJa8GJqFwQNgNrMuww # ServeTheHome
                    - UC1LpsuAUaKoMzzJSEt5WImw # Asianometry
                    - UC9PBzalIcEQCsiIkq36PyUA # Digital Foundry
                    - UCSNsJvvc3LarXVkJ2H6e2zQ # Michael Hendriks
                    - UCD80bzqJh1N7lOqn7n0vKTg # Nilaus
                    - UCMb0O2CdPBNi-QqPk5T3gsQ # James Hoffmann
                    - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium
      
                - type: group
                  widgets:
                    - type: reddit
                      subreddit: factorio
                      show-thumbnails: true
                    - type: reddit
                      subreddit: selfhosted
                      show-thumbnails: true
      
            - size: small
              widgets:
                - type: weather
                  location: San Francisco, California, United States
                  units: metric
                  hour-format: 24h
      
                - type: markets
                  markets:
                    - symbol: SPY
                      name: S&P 500
                    - symbol: NVDA
                      name: NVIDIA
                    - symbol: AAPL
                      name: Apple
                    - symbol: MSFT
                      name: Microsoft
                    - symbol: GOOGL
                      name: Google
                    - symbol: AMD
                      name: AMD
      
                - type: releases
                  cache: 1d
                  # Without authentication the Github API allows for up to 60 requests per hour. You can create a
                  # read-only token from your Github account settings and use it here to increase the limit.
                  # token: ...
                  repositories:
                    - glanceapp/glance
                    - siderolabs/talos
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: glance
  name: glance
  namespace: glance
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glance-ingress
  namespace: glance
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: ingress-nginx-internal
  rules:
  - host: glance.<path:stringreplacesecret#domain>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: glance
            port:
              number: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: glance-http
  namespace: glance
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  parentRefs:
    - name: internal
      namespace: gateway
      sectionName: https
    - name: external
      namespace: gateway
      sectionName: https
  hostnames:
  - "glance.<path:stringreplacesecret#domain>"
  rules:
    - backendRefs:
      - name: glance
        port: 80
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: glance-external
  namespace: glance
  annotations:
    external-dns.custom/type: public
spec:
  endpoints:
    - dnsName: glance.<path:stringreplacesecret#domain>
      recordType: CNAME
      targets:
        - ingress.<path:stringreplacesecret#domain>
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: glance
  namespace: glance
  annotations:
    external-dns.custom/type: private
spec:
  endpoints:
    - dnsName: glance.<path:stringreplacesecret#domain>
      recordType: CNAME
      targets:
        - intgw.<path:stringreplacesecret#domain>
      providerSpecific:
