---
kind: Namespace
apiVersion: v1
metadata:
  name: glance
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glance
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    chart: app-template
    repoURL: http://bjw-s.github.io/helm-charts/
    targetRevision: 3.7.3
    helm:
      values: |
        # fullnameOverride: *name
        # defaultPodOptions:
        #   securityContext:
        #     runAsNonRoot: true
        #     runAsUser: 1022
        #     runAsGroup: 1022
        #     fsGroup: 1022
        #     fsGroupChangePolicy: OnRootMismatch
        #     seccompProfile:
        #       type: RuntimeDefault
        controllers:
          glance:
            strategy: RollingUpdate
            annotations:
              reloader.stakater.com/auto: "true"
            containers:
              glance:
                image:
                  repository: glanceapp/glance
                  tag: v0.7.3@sha256:ecf8c49224cff1264fc028eea9a91cd8fb5aab39ab75c0bebd30235ef42d0cab
                args:
                  - --config
                  - /config/glance.yaml
                env:
                  TZ: "${TIMEZONE}"
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities: { drop: ["ALL"] }
        service:
          app:
            controller: glance
            type: ClusterIP
            ports:
              http:
                port: 8080
        persistence:
           config:
             enabled: true
             type: configMap
             name: glance-configmap
           data:
            enabled: true
            existingClaim: glance
            advancedMounts:
              glance:
                app:
                  - path: /config/glance.yaml
          #  config-storage:
          #    enabled: true
          #    type: emptyDir
          #    globalMounts:
          #      - path: /config
  destination:
    server: https://kubernetes.default.svc
    namespace: glance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-configmap
  namespace: glance
  labels:
    app.kubernetes.io/name: glance
data:
  glance.yaml: |
    theme:
      background-color: 240 21 15
      contrast-multiplier: 1.2
      primary-color: 217 92 83
      positive-color: 115 54 76
      negative-color: 347 70 65
    pages:
      - name: Home
        columns:
          - size: small
            widgets:
              - type: calendar

              - type: rss
                limit: 10
                collapse-after: 3
                cache: 3h
                feeds:
                  - url: https://ciechanow.ski/atom.xml
                  - url: https://www.joshwcomeau.com/rss.xml
                    title: Josh Comeau
                  - url: https://samwho.dev/rss.xml
                  - url: https://awesomekling.github.io/feed.xml
                  - url: https://ishadeed.com/feed.xml
                    title: Ahmad Shadeed

              - type: twitch-channels
                channels:
                  - ferretsoftware
                  - theprimeagen
                  - cohhcarnage
                  - christitustech
                  - blurbs
                  - asmongold
                  - jembawls

          - size: full
            widgets:
              - type: hacker-news

              - type: videos
                channels:
                  - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
                  - UCv6J_jJa8GJqFwQNgNrMuww # ServeTheHome
                  - UCOk-gHyjcWZNj3Br4oxwh0A # Techno Tim

              - type: reddit
                subreddit: selfhosted

          - size: small
            widgets:
              - type: weather
                location: Eugene, Oregon, United States

              - type: monitor
                cache: 1m
                title: Services
                sites:
                  - title: Home Assistant
                    url: https://hass.ok8.sh
                  - title: Grafana
                    url: https://grafana.ok8.sh
                  - title: ID
                    url: https://id.ok8.sh
                  - title: DynMC
                    url: https://dynmc.ok8.sh
  style.css:  |
      /* ==========================================================================
      BASE & GENERAL STYLES
      ========================================================================== */

      html, body {
        overflow-x: hidden;
      }

      body {
        --color-widget-background: rgba(9, 11, 16, 0);
        --color-primary: hsl(210.46deg 16% 76.94%);
        --color-positive: hsl(116.2deg 34.43% 28%);
        --border-radius: 10px;
        font-family: system-ui;
        background-image: url("/assets/glc-wp.png");1948744
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
        position: relative; 
      }

      @keyframes fadeIn {
        from { opacity: 0; }
        to { opacity: 1; }
      }

      /* Header & Layout Components */
      .header {
        -webkit-box-shadow: 0 7px 9px -1px rgb(0 0 0 / 50%);
        -moz-box-shadow: 0 7px 9px -1px rgb(0 0 0 / 50%);
        box-shadow: 0 7px 9px -1px rgb(0 0 0 / 50%);
      }

      .widget-header {
        text-shadow: 0 0 5px black !important;
        overflow: visible !important;
        display: flex;
        align-items: center;
        width: 100%;
        position: relative;
        padding-right: 5px;
      }

      .widget-header:after {
        content: "";
        display: inline-block;
        height: 5px;
        background: #5d5d5d33;
        flex-grow: 1;
        margin-left: 5px;
      }

      .widget-group-title {
        padding-right: 0px;
      }

      .widget-content:not(.widget-content-frameless) {
        box-shadow: 0px 3px 18px 0px hsl(var(--bghs), calc(var(--scheme) (var(--scheme) var(--bgl)) - 4.5%));
        background: rgba(0, 0, 0, 0.70);
      }

      .widget-content-frame {
        background: rgba(0, 0, 0, 0.70);
      }

      /* ==========================================================================
        COMPONENT STYLES
        ========================================================================== */

      /* iFrame Widget */

      /* Proxmox Widget */
      iframe[src="https://your_iframe_url_1"] {
        opacity: 0;
        animation: fadeIn 0.5s ease 0.5s forwards;
        width: 800px;
        height: 700px;
        overflow: hidden;
        transform: scale(0.4);
        transform-origin: 0 0;
      }

      /* Weather Widget */
      iframe[src="https://your_iframe_url_2"] {
        opacity: 0;
        animation: fadeIn 0.5s ease 0.5s forwards;
        overflow: hidden;
        transform: scale(0.8);
        transform-origin: 0 0;
        width: 380px;
        height: 160px;
      }

      .widget-content.widget-content-frameless:has(iframe[src="https://your_iframe_url_2"]) {
        height: 130px;
      }

      /* Cards & List Items */
      .cards-grid.collapsible-container + .expand-toggle-button {
        background: rgba(0, 0, 0, 0.70);
        border-radius: 10px;
      }

      li {
        transition: all 200ms ease;
      }

      li:hover:not(.flex) {
        background-color: color-mix(in srgb, var(--color-widget-background) 95%, white 5%);
        padding-left: 5px;
        border-radius: 5px;
        transition: all 200ms ease;
      }

      li.flex {
        position: relative;
      }

      li.flex:hover {
        background-color: color-mix(in srgb, var(--color-widget-background) 95%, white 5%);
        border-radius: 5px;
      }

      li.flex.items-center.gap-10 {
        display: inline-block;
        width: calc(50% - 1rem);
        place-items: center;
      }

      /* Bookmarks */
      li.flex a.bookmarks-link {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: 1;
        display: flex;
        align-items: center;
        justify-content: flex-start;
        flex-direction: column-reverse;
      }

      li.flex .bookmarks-icon-container img {
        transition: transform 0.2s ease;
      }

      li.flex:hover .bookmarks-icon-container img {
        transform: scale(1.2);
      }

      .bookmarks-group .list.list-gap-2 li:nth-child(2n+3) {
        margin-top: 1rem;
      }

      .bookmarks-icon {
        opacity: 1;
      }

      .bookmarks-icon-container {
        margin-bottom: 2rem;
      }

      .items-center {
        transition: all 200ms ease;
      }

      /* Forum & Dynamic Columns */
      .forum-post-list-thumbnail {
        width: 10rem;
        height: 6rem;
      }

      .dynamic-columns > :not(:nth-child(3n+1)):hover:not(.bookmarks-group) {
        background-color: color-mix(in srgb, var(--color-widget-background) 95%, white 5%);
        padding-left: calc(var(--widget-content-horizontal-padding) + 5px);
        border-radius: 10px;
        transition: all 200ms ease;
      }

      .dynamic-columns > :nth-child(3n+1):hover:not(.bookmarks-group) {
        background-color: color-mix(in srgb, var(--color-widget-background) 95%, white 5%);
        padding-left: 5px;
        border-radius: 10px;
        transition: all 200ms ease;
      }

      /* ==========================================================================
        MEDIA QUERIES (OPTIONAL)
        ========================================================================== */

      @media (max-width: 650px) {
        html {
          scrollbar-width: none;
        }

        body {
          --color-background: transparent;
          background-image: none !important;
        }

        .page {
          padding-block: unset !important;
        }

        .header {
          display: none;
        }

        .widget-header {
          display: none !important;
        }

        .mobile-navigation {
          display: none !important;
        }
      }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: glance
  name: glance
  namespace: glance
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glance-ingress
  namespace: glance
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: ingress-nginx-internal
  rules:
  - host: glance.<path:stringreplacesecret#domain>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: glance
            port:
              number: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: glance-http
  namespace: glance
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  parentRefs:
    - name: internal
      namespace: gateway
      sectionName: https
    - name: external
      namespace: gateway
      sectionName: https
  hostnames:
  - "glance.<path:stringreplacesecret#domain>"
  rules:
    - backendRefs:
      - name: glance
        port: 80
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: glance-external
  namespace: glance
  annotations:
    external-dns.custom/type: public
spec:
  endpoints:
    - dnsName: glance.<path:stringreplacesecret#domain>
      recordType: CNAME
      targets:
        - ingress.<path:stringreplacesecret#domain>
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: glance
  namespace: glance
  annotations:
    external-dns.custom/type: private
spec:
  endpoints:
    - dnsName: glance.<path:stringreplacesecret#domain>
      recordType: CNAME
      targets:
        - intgw.<path:stringreplacesecret#domain>
      providerSpecific: