---
kind: Namespace
apiVersion: v1
metadata:
  name: glance
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glance
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    chart: app-template
    repoURL: https://bjw-s-labs.github.io/helm-charts
    targetRevision: 4.1.2
    helm:
      values: |
        controllers:
          glance:
            strategy: RollingUpdate
            annotations:
              reloader.stakater.com/auto: "true"
            containers:
              glance:
                image:
                  repository: glanceapp/glance
                  tag: v0.8.4@sha256:6df86a7e8868d1eda21f35205134b1962c422957e42a0c44d4717c8e8f741b1a
                args:
                  - --config
                  - /config/glance.yaml
                env:
                  TZ: "${TIMEZONE}"
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities: { drop: ["ALL"] }
        service:
          app:
            controller: glance
            type: ClusterIP
            ports:
              http:
                port: 8080
        persistence:
           config:
             enabled: true
             type: configMap
             name: glance-configmap
           data:
            enabled: true
            existingClaim: glance
            advancedMounts:
              glance:
                app:
                  - path: /config/glance.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: glance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-configmap
  namespace: glance
  labels:
    app.kubernetes.io/name: glance
data:
  glance.yaml: |
    pages:
      - name: Startpage
        # width: slim
        # hide-desktop-navigation: false
        # center-vertically: true
        head-widgets:
          - type: markets
            hide-header: true
            markets:
              - symbol: SPY
                name: S&P 500
              - symbol: BTC-USD
                name: Bitcoin
              - symbol: NVDA
                name: NVIDIA
              - symbol: AAPL
                name: Apple
        columns:
          - size: small
            widgets:
              - type: calendar

          - size: full
            widgets:
              - type: search
                search-engine: https://search.marcthespot.com/search?q={QUERY}
                autofocus: true

              - type: monitor
                cache: 1m
                title: Services
                sites:
                  - title: Jellyfin
                    url: https://jellyfin.marcthespot.com/
                    icon: si:jellyfin
                  - title: Radarr
                    url: https://radarr.marcthespot.com/
                    icon: si:radarr
                  - title: Sonarr
                    url: https://Sonarr.marcthespot.com/
                    icon: si:sonarr      
                  - title: Homeassistant
                    url: http://192.168.1.210:8123
                    icon: si:homeassistant
                  - title: Truenas
                    url: http://192.168.1.235
                    icon: si:truenas
                  - title: Argocd
                    url: https://argocd.marcthespot.com/
                    icon: si:argocd
                  - title: Immich
                    url: https://immich.marcthespot.com/
                    icon: si:immich
                  - title: Transmission
                    url: https://transmission.marcthespot.com/
                    icon: si:transmission
                  - title: Longhorn
                    url: https://lh.marcthespot.com/
                    icon: si:longhorn
                  - title: Paperless
                    url: https://paperless.marcthespot.com/
                    icon: si:paperless-ngx
                  - title: OpenWebUi
                    url: https://webui.marcthespot.com/
                    icon: si:ollama
              - type: bookmarks
                groups:      
                  - title: General
                    links:
                      - title: Gmail
                        url: https://mail.google.com/mail/u/0/
                      - title: Amazon
                        url: https://www.amazon.com/
                      - title: Github
                        url: https://github.com/
                      - title: Chase 
                        url: https://chase.com/
                  - title: Entertainment
                    links:
                      - title: YouTube
                        url: https://youtube.com/
                      - title: Netflix
                        url: https://netflix.com/
                      - title: NHL
                        url: https://www.nhl.com/
                      - title: Peacock
                        url: https://www.peacocktv.com/
                  - title: Social
                    links:
                      - title: Reddit
                        url: https://reddit.com/
                      - title: X
                        url: https://x.com/
                      - title: Facebook
                        url: https://facebook.com
                      - title: Instagram
                        url: https://instagram.com
                  - title: 3D Printing
                    links:
                      - title: Bambu Lab
                        url: https://makerworld.com/
                      - title: Thangs
                        url: https://www.thangs.com
                      - title: Thingiverse
                        url: https://www.thingiverse.com/
                      - title: Printables
                        url: https://www.printables.com/    
                      - title: MyMiniFactory
                        url: https://www.myminifactory.com/
                      - title: Cults3D
                        url: https://cults3d.com/en
                  - title: School
                    links:
                      - title: WGU
                        url: https://my.wgu.edu/
          - size: small
            widgets:
              - type: weather
                location: South Huntington, New York, United States
                units: imperial
                show-forecast: true
                show-wind: true            
                      
      - name: Resources
        columns:
          - size: full
            widgets:
              - type: group
                widgets:
                  - type: reddit
                    show-thumbnails: true
                    subreddit: unixporn
                  - type: reddit
                    subreddit: hyprland
                    show-thumbnails: true
                  - type: reddit
                    subreddit: bambulab
                    show-thumbnails: true
                  - type: reddit
                    subreddit: 3Dprinting
                    show-thumbnails: true
                  - type: reddit
                    subreddit: archlinux
                    show-thumbnails: true
                  - type: reddit
                    subreddit: wallpaperengine
                    show-thumbnails: true
                  - type: reddit
                    subreddit: longisland
                    show-thumbnails: true
                  - type: reddit
                    subreddit: homeassistant
                    show-thumbnails: true
                  - type: reddit
                    subreddit: selfhosted 
                    show-thumbnails: true
                  - type: reddit
                    subreddit: ufos
                    show-thumbnails: true
                  - type: reddit
                    subreddit: linux_gaming
                    show-thumbnails: true

              - type: videos
                style: grid-cards
                collapse-after-rows: 3
                channels:
                  - UCcLYOTz3ct6_lk9iLToxxAw # Mat Armstrong
                  - UCvEq9e3q3yb-qXge2ALgzCA # Jack Builds it
                  - UC9x0AN7BWHpCDHSm9NiJFJQ# NetworkChuck
                  - UCvAhDxNNUDhi78tMXVGBUaQ # Tavarish
                  - UCF0pVplsI8e0KYx3X9s6g4A # Linus Tech Tips
                  - UCOk-gHyjcWZNj3Br4oxwh0A # Techno Tim
                  - UCe-5wDW9r3-C0HVdcm9_knA # Kalle Flodin
                  - UCxByVUuLdxxiqQVmbOnDEzw # Erik Grankvist


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: glance
  name: glance
  namespace: glance
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glance-ingress
  namespace: glance
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: ingress-nginx-internal
  rules:
  - host: glance.<path:stringreplacesecret#domain>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: glance
            port:
              number: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: glance-http
  namespace: glance
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  parentRefs:
    - name: internal
      namespace: gateway
      sectionName: https
    - name: external
      namespace: gateway
      sectionName: https
  hostnames:
  - "glance.<path:stringreplacesecret#domain>"
  rules:
    - backendRefs:
      - name: glance
        port: 80
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: glance-external
  namespace: glance
  annotations:
    external-dns.custom/type: public
spec:
  endpoints:
    - dnsName: glance.<path:stringreplacesecret#domain>
      recordType: CNAME
      targets:
        - ingress.<path:stringreplacesecret#domain>
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: glance
  namespace: glance
  annotations:
    external-dns.custom/type: private
spec:
  endpoints:
    - dnsName: glance.<path:stringreplacesecret#domain>
      recordType: CNAME
      targets:
        - intgw.<path:stringreplacesecret#domain>
      providerSpecific:
