---
kind: Namespace
apiVersion: v1
metadata:
  name: glance
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glance
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    chart: app-template
    repoURL: https://bjw-s-labs.github.io/helm-charts
    targetRevision: 3.7.1
    helm:
      values: |
        controllers:
          glance:
            strategy: RollingUpdate
            annotations:
              reloader.stakater.com/auto: "true"
            containers:
              glance:
                image:
                  repository: glanceapp/glance
                  tag: v0.7.9@sha256:6e14662ffe83d4bf4e09314d27ee233d51f3ed2dc7322c4d4b18c929177c4117
                args:
                  - --config
                  - /config/glance.yaml
                env:
                  TZ: "${TIMEZONE}"
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities: { drop: ["ALL"] }
        service:
          app:
            controller: glance
            type: ClusterIP
            ports:
              http:
                port: 8080
        persistence:
           config:
             enabled: true
             type: configMap
             name: glance-configmap
           data:
            enabled: true
            existingClaim: glance
            advancedMounts:
              glance:
                app:
                  - path: /config/glance.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: glance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-configmap
  namespace: glance
  # labels:
  #   app.kubernetes.io/name: glance
data:
  glance.yaml: |
    theme:
      background-color: 240 21 15
      contrast-multiplier: 1.2
      primary-color: 217 92 83
      positive-color: 115 54 76
      negative-color: 347 70 65
    pages:
      - name: Home
        columns:
          - size: small
            widgets:
              - type: calendar

              - type: rss
                limit: 10
                collapse-after: 3
                cache: 3h
                feeds:
                  - url: https://ciechanow.ski/atom.xml
                  - url: https://www.joshwcomeau.com/rss.xml
                    title: Josh Comeau
                  - url: https://samwho.dev/rss.xml
                  - url: https://awesomekling.github.io/feed.xml
                  - url: https://ishadeed.com/feed.xml
                    title: Ahmad Shadeed

              - type: twitch-channels
                channels:
                  - ferretsoftware
                  - theprimeagen
                  - cohhcarnage
                  - christitustech
                  - blurbs
                  - asmongold
                  - jembawls

          - size: full
            widgets:
              - type: hacker-news

              - type: videos
                channels:
                  - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
                  - UCv6J_jJa8GJqFwQNgNrMuww # ServeTheHome
                  - UCOk-gHyjcWZNj3Br4oxwh0A # Techno Tim

              - type: reddit
                subreddit: selfhosted

          - size: small
            widgets:
              - type: weather
                location: New York, New York, United States

              - type: monitor
                cache: 1m
                title: Services
                sites:
                  - title: Home Assistant
                    url: https://hass.ok8.sh
                  - title: Grafana
                    url: https://grafana.ok8.sh
                  - title: ID
                    url: https://id.ok8.sh
                  - title: DynMC
                    url: https://dynmc.ok8.sh
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: glance
  name: glance
  namespace: glance
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glance-ingress
  namespace: glance
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: ingress-nginx-internal
  rules:
  - host: glance.<path:stringreplacesecret#domain>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: glance
            port:
              number: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: glance-http
  namespace: glance
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  parentRefs:
    - name: internal
      namespace: gateway
      sectionName: https
    - name: external
      namespace: gateway
      sectionName: https
  hostnames:
  - "glance.<path:stringreplacesecret#domain>"
  rules:
    - backendRefs:
      - name: glance
        port: 80
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: glance-external
  namespace: glance
  annotations:
    external-dns.custom/type: public
spec:
  endpoints:
    - dnsName: glance.<path:stringreplacesecret#domain>
      recordType: CNAME
      targets:
        - ingress.<path:stringreplacesecret#domain>
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: glance
  namespace: glance
  annotations:
    external-dns.custom/type: private
spec:
  endpoints:
    - dnsName: glance.<path:stringreplacesecret#domain>
      recordType: CNAME
      targets:
        - intgw.<path:stringreplacesecret#domain>
      providerSpecific: