---
kind: Namespace
apiVersion: v1
metadata:
  name: glance
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glance
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    chart: app-template
    repoURL: http://bjw-s.github.io/helm-charts/
    targetRevision: 3.7.2
    helm:
      values: |
        fullnameOverride: *name
        defaultPodOptions:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1022
            runAsGroup: 1022
            fsGroup: 1022
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
        controllers:
          glance:
            strategy: RollingUpdate
            annotations:
              reloader.stakater.com/auto: "true"
            containers:
              glance:
                image:
                  repository: docker.io/glanceapp/glance
                  tag: v0.7.3@sha256:ecf8c49224cff1264fc028eea9a91cd8fb5aab39ab75c0bebd30235ef42d0cab
                args:
                  - --config
                  - /config/glance.yaml
                env:
                  TZ: "${TIMEZONE}"
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities: { drop: ["ALL"] }
        service:
          glance:
            controller: *name
            ports:
              http:
                port: 8080
        ingress:
          glance:
            enabled: true
            annotations:
              haproxy.org/allow-list: "${HAPROXY_WHITELIST}"
              haproxy.org/ssl-redirect-port: "443"
              haproxy.org/response-set-header: |
                Strict-Transport-Security "max-age=31536000"
                X-Frame-Options "DENY"
                X-Content-Type-Options "nosniff"
                Referrer-Policy "no-referrer-when-downgrade"
            hosts:
              - host: &host "glance.${SECRET_DEFAULT_DOMAIN}"
                paths:
                  - path: /
                    service:
                      identifier: glance
                      port: http
            tls:
              - hosts:
                  - *host
        persistence:
          config:
            type: configMap
            name: glance-config
destination:
  server: https://kubernetes.default.svc
  namespace: ollama
syncPolicy:
  automated:
    prune: true
    selfHeal: true

