---
# Source: guacamole/templates/configmaps.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-guacamole-guacd-configs
data:
---
# Source: guacamole/templates/configmaps.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-guacamole-app-configs
data:
---
# Source: guacamole/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-guacamole-guacd
  labels:
    app: guacamole-guacd
    chart: guacamole-1.0.0
    release: my-guacamole
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 4822
      targetPort: 4822
      protocol: TCP
      name: guacd
  selector:
    app: guacamole-guacd
    release: my-guacamole
---
# Source: guacamole/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-guacamole-app
  labels:
    app: guacamole-app
    chart: guacamole-1.0.0
    release: my-guacamole
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: guacamole
  selector:
    app: guacamole-app
    release: my-guacamole
---
# Source: guacamole/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-guacamole-guacd
  labels:
    app: guacamole-guacd
    chart: guacamole-1.0.0
    draft: draft-app
    release: my-guacamole
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole-guacd
      release: my-guacamole
  template:
    metadata:
      labels:
        app: guacamole-guacd
        draft: draft-app
        release: my-guacamole
      annotations:
        buildID: ""
    spec:
      containers:
        - name: guacd
          image: "guacamole/guacd:1.5.5"
          imagePullPolicy: IfNotPresent
          ports:
            - name: guacd
              containerPort: 4822
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 300
            periodSeconds: 60
            tcpSocket:
              port: 4822
          readinessProbe:
            initialDelaySeconds: 300
            periodSeconds: 60
            tcpSocket:
              port: 4822
          envFrom:
            - configMapRef:
                name: my-guacamole-guacd-configs
          resources:
            limits:
              cpu: 40m
              memory: 512Mi
            requests:
              cpu: 20m
              memory: 300Mi
          securityContext:
            allowPrivilegeEscalation: false
---
# Source: guacamole/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-guacamole-app
  labels:
    app: guacamole-app
    chart: guacamole-1.0.0
    draft: draft-app
    release: my-guacamole
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole-app
      release: my-guacamole
  template:
    metadata:
      labels:
        app: guacamole-app
        draft: draft-app
        release: my-guacamole
      annotations:
        buildID: ""
    spec:
      containers:
        - name: guacamole
          image: "guacamole/guacamole:1.5.5"
          imagePullPolicy: IfNotPresent
          ports:
            - name: guacamole
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 300
            periodSeconds: 60
            tcpSocket:
              port: 8080
          readinessProbe:
            initialDelaySeconds: 300
            periodSeconds: 60
            tcpSocket:
              port: 8080
          envFrom:
            - configMapRef:
                name: my-guacamole-app-configs
          resources:
            limits:
              cpu: 40m
              memory: 512Mi
            requests:
              cpu: 20m
              memory: 300Mi
          securityContext:
            allowPrivilegeEscalation: false
