---
kind: Namespace
apiVersion: v1
metadata:
  name: homepage
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  destination: 
    namespace: homepage
    server: https://kubernetes.default.svc
  sources:
  - chart: homepage
    repoURL: http://jameswynn.github.io/helm-charts
    targetRevision: 1.2.3
    helm:
      valueObject:
        image:
          repository: ghcr.io/jameswynn/homepage
          tag: kubernetes
          pullPolicy: Always
        enableRbac: true
        serviceAccount:
          create: true
          name: homepage-test
        config:
          kubernetes:
            mode: cluster
          widgets:
            - resources:
                backend: kubernetes
                expanded: true
                cpu: true
                memory: true
        service:
          main:
            ports:
              http:
                port: 3000
