---
kind: Namespace
apiVersion: v1
metadata:
  name: homepage
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  sources:
  - chart: homepage
    repoURL: http://jameswynn.github.io/helm-charts
    targetRevision: 1.2.3
    helm:
      valueObject:
        image:
          repository: ghcr.io/gethomepage/homepage
          tag: v0.8.13

        enableRbac: false

        serviceAccount:
          # Specify a different service account name
          name: homepage
          # Create service account. Needed when RBAC is enabled.
          create: false

        service:
          main:
            ports:
              http:
                port: 3000

        controller:
          strategy: RollingUpdate
          rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
