---
kind: Namespace
apiVersion: v1
metadata:
  name: immich
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - chart: immich
    repoURL: https://immich-app.github.io/immich-charts
    targetRevision: 0.4.0
    helm:
      valueFiles:
      - $repo/manifest/values/immich-values.yaml
      releaseName: immich
  - repoURL: https://github.com/marcthespot0/home-lab
    path: /manifest/
    targetRevision: main
    ref: repo
  destination:
    name: in-cluster
    namespace: immich
  ignoreDifferences:
  - kind: PersistentVolume
    jsonPointers:
    - /spec/claimRef/resourceVersion
    - /spec/claimRef/uid
    - /status/lastPhaseTransitionTime
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true