apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    chart: immich
    repoURL: https://immich-app.github.io/immich-charts
    targetRevision: '*'
    helm:
      releaseName: immich-release
      values: |
        immich:
          persistence:
            # Main data store for all photos shared between different components.
            library:
              # Automatically creating the library volume is not supported by this chart
              # You have to specify an existing PVC to use
              existingClaim: media-nfs
        postgresql:
          enabled: true
        redis:
          enabled: true
        service:
          main:
            type: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: immich
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-main-pvc
  namespace: immich
spec:
  storageClassName: media-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # NFS Subdir Provisioner doesn't care at all abou this
      storage: 100M