---
kind: Namespace
apiVersion: v1
metadata:
  name: immich
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-photos
  namespace: immich
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-nfs-csi"
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    chart: immich
    repoURL: https://immich-app.github.io/immich-charts
    targetRevision: '*'
    helm:
      releaseName: immich-release
      values: |
        immich:
          persistence:
            # Main data store for all photos shared between different components.
            library:
              # Automatically creating the library volume is not supported by this chart
              # You have to specify an existing PVC to use
              existingClaim: immich-photos
        postgresql:
          enabled: true
        redis:
          enabled: true
        service:
          main:
            type: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: immich
  syncPolicy:
    syncOptions:
    automated:
      prune: true
      selfHeal: true 
