---
kind: Namespace
apiVersion: v1
metadata:
  name: jellyfin
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - chart: app-template
    repoURL: https://bjw-s.github.io/helm-charts/
    targetRevision: 3.0.2
    helm:
      valuesObject:
        controllers:
        main:
          type: statefulset

          statefulset:
            volumeClaimTemplates:
              - name: config
                accessMode: ReadWriteOnce
                size: 30Gi
                storageClass: local-path
                globalMounts:
                  - path: /config

          pod:
            enableServiceLinks: false
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              fsGroup: 568
              fsGroupChangePolicy: "OnRootMismatch"
              supplementalGroups:
                - 44
                - 109

          containers:
            jellyfin:
              image:
                repository: docker.io/jellyfin/jellyfin
                tag: 2024032802-amd64
              env:
                DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
                JELLYFIN_FFmpeg__probesize: 50000000
                JELLYFIN_FFmpeg__analyzeduration: 500000000
                JELLYFIN_PublishedServerUrl: 172.16.1.24
              resources:
                requests:
                  cpu: 100m
                  memory: 9248M
                limits:
                  memory: 9248M

      service:
        jellyfin:
          controller: main
          ports: &ports
            http:
              port: 8096

      persistence:
        config:
          existingClaim: jellyfin
        music:
          existingClaim: music
        movies:
          existingClaim: movies
        audio:
          existingClaim: audio
        tv-shows:
          existingClaim: tv-shows
        transcode:
          type: emptyDir
        cache:
          type: emptyDir
            releaseName: jellyfin
        - repoURL: https://github.com/clearlybaffled/homelab
          path: cluster/apps/media/jellyfin
          targetRevision: main
          ref: repo
        destination:
          name: in-cluster
          namespace: hwllydin
        ignoreDifferences:
        - group: apps
          kind: StatefulSet
          jsonPointers:
          - /spec/volumeClaimTemplates
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
      ---
      # yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/library/common/values.schema.json
