---
kind: Namespace
apiVersion: v1
metadata:
  name: nextcloud
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        NEXTCLOUD_USER: "{{ .NEXTCLOUD_USERNAME }}"
        NEXTCLOUD_PASS: "{{ .NEXTCLOUD_PASSWORD }}"
    data:
      - secretKey: NEXTCLOUD_USERNAME
        remoteRef:
          key: nextcloud
          property: nextclouduser
      - secretKey: NEXTCLOUD_PASSSWORD
        remoteRef:
          key: nextcloud
          property: nextcloudpass
---
apiVersion: v1
kind: Service
metadata:
  name: my-nextcloud
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    helm.sh/chart: nextcloud-5.5.2
    app.kubernetes.io/instance: my-nextcloud
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/instance: my-nextcloud
    app.kubernetes.io/component: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nextcloud
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    helm.sh/chart: nextcloud-5.5.2
    app.kubernetes.io/instance: my-nextcloud
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
      app.kubernetes.io/instance: my-nextcloud
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nextcloud
        app.kubernetes.io/instance: my-nextcloud
        app.kubernetes.io/component: app
      annotations:
        nextcloud-config-hash: b1c70036bd50622dc3b0c6b7991ee4df26867655ecf455cc2fede9350b4e063a
        php-config-hash: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
        hooks-hash: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:29.0.4-apache
          imagePullPolicy: IfNotPresent
          env:
            
            - name: SQLITE_DATABASE
              value: "nextcloud"
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: NEXTCLOUD_USER
                  key: nextcloud
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: NEXTCLOUD_PASS
                  key: nextcloud
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: nextcloud.kube.home
            - name: NEXTCLOUD_DATA_DIR
              value: "/var/www/html/data"
            
            
            
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status.php
              port:  80
              httpHeaders:
              - name: Host
                value: "nextcloud.kube.home"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /status.php
              port:  80
              httpHeaders:
              - name: Host
                value: "nextcloud.kube.home"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            {}
          volumeMounts:
            - name: nextcloud-main
              mountPath: /var/www/
              subPath: root
            - name: nextcloud-main
              mountPath: /var/www/html
              subPath: html
            - name: nextcloud-main
              mountPath: /var/www/html/data
              subPath: data
            - name: nextcloud-main
              mountPath: /var/www/html/config
              subPath: config
            - name: nextcloud-main
              mountPath: /var/www/html/custom_apps
              subPath: custom_apps
            - name: nextcloud-main
              mountPath: /var/www/tmp
              subPath: tmp
            - name: nextcloud-main
              mountPath: /var/www/html/themes
              subPath: themes
      volumes:
        - name: nextcloud-main
          persistentVolumeClaim:
            claimName: nextcloud-data
      securityContext:
        fsGroup: 33
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-data
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
