apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-livesync-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obsidian-livesync-couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obsidian-livesync-couchdb
  template:
    metadata:
      labels:
        app: obsidian-livesync-couchdb
    spec:
      containers:
      - name: couchdb
        image: couchdb:3.2.2
        volumeMounts:
        - name: obsidian-livesync-data
          mountPath: /var/lib/couchdb/data
        ports:
        - containerPort: 5984
        env:
        - name: COUCHDB_USER
          value: "admin"
        - name: COUCHDB_PASSWORD
          value: "password"
        - name: COUCHDB_UUID
          value: "obsidian-livesync"
        - name: COUCHDB_SINGLE_NODE
          value: "true"

---

apiVersion: v1
kind: Service
metadata:
  name: obsidian-livesync-couchdb
spec:
  selector:
    app: obsidian-livesync-couchdb
  ports:
  - name: couchdb
    port: 5984
  type: LoadBalancer