apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obsidian-livesync
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: charts/obsidian-livesync
    repoURL: https://github.com/heywoodlh/gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-config
data:
  couchdb.yaml: |-
    {
      "couchdb": {
        "single_node": true,
        "uuid": "obsidian-livesync"
      },
      "chttpd": {
        "bind_address": "any",
        "require_valid_user": true
      },
      "chttpd_auth": {
        "require_valid_user": true,
        "authentication_redirect": "/_utils/session.html"
      },
      "httpd": {
        "WWW-Authenticate": 'Basic realm="couchdb"'
      },
      "cors": {
        "origins": ["app://obsidian.md", "capacitor://localhost", "http://localhost"],
        "credentials": true,
        "headers": ["accept", "authorization", "content-type", "origin", "referer"],
        "methods": ["GET", "PUT", "POST", "HEAD", "DELETE"],
        "max_age": 3600
      }
    }

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-livesync-couchdb-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - image: couchdb:3.3.3
        name: couchdb
        env:
          - name: COUCHDB_USER
            value: admin
          - name: COUCHDB_PASSWORD
            value: password
        command: ["sh", "-c", "couchdb -e '_users' && couchdb -e '_replicator'"]
        volumeMounts:
        - name: couchdb-data
          mountPath: /opt/couchdb/data
      volumes:
      - name: couchdb-data
        persistentVolumeClaim:
          claimName: obsidian-livesync-couchdb-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: couchdb
spec:
  selector:
    app: couchdb
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: LoadBalancer