---
kind: Namespace
apiVersion: v1
metadata:
  name: obsidian
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obsidian-livesync
  namespace: obsidian
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://bjw-s.flux-system:flux'
    targetRevision: 'HEAD'
    path: 'app-template/'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  values:
    controllers:
      obsidian-livesync:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          - name: init-config
            image: public.ecr.aws/docker/library/busybox
            command:
              - /bin/sh
              - -c
              - cp /tmp/config/*.ini /opt/couchdb/etc/default.d/; ls -lrt /opt/couchdb/etc/default.d/
        containers:
          - name: app
            image: public.ecr.aws/docker/library/couchdb
            env:
              - name: TZ
                value: America/New_York
            envFrom:
              - configMapKeyRef:
                  name: obsidian-livesync-secret
                  key: password
            ports:
              - containerPort: 5984
        service:
          - name: app
            type: ClusterIP
            selector:
              app: obsidian-livesync-app
    persistence:
      config:
        type: ConfigMap
        name: obsidian-livesync-configmap
      data:
        existingClaim: obsidian-livesync-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: obsidian-livesync-app
  namespace: obsidian
spec:
  selector:
    app: obsidian-livesync
  ports:
  - name: http
    port: 5984
    targetPort: 5984
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-livesync-data
  namespace: obsidian
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi