apiVersion: v1
kind: Namespace
metadata:
  name: obsidian-livesync
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-livesync-couchdb-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - name: couchdb
        image: couchdb:3.2.2
        volumeMounts:
        - name: data
          mountPath: /var/lib/couchdb/data
        env:
        - name: COUCHDB_URL
          value: http://couchdb:5984
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: obsidian-livesync-couchdb-data


---

apiVersion: v1
kind: Service
metadata:
  name: couchdb
spec:
  selector:
    app: couchdb
  ports:
  - name: http
    port: 5984
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-livesync-couchdb-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
