---
kind: Namespace
apiVersion: v1
metadata:
  name: obsidian-livesync
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: obsidian-couchdb
  namespace: obsidian-livesync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: obsidian-couchdb-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        COUCHDB_USER: "{{ .OBSIDIAN_COUCHDB_USER }}"
        COUCHDB_PASSWORD: "{{ .OBSIDIAN_COUCHDB_PASSWORD }}"
  dataFrom:
    - extract:
        key: obsidian
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obsidian-livesync
  namespace: argocd
spec:
  destination:
    namespace: obsidian-livesync
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: app-template 
    repoURL: http://bjw-s.github.io/helm-charts/
    targetRevision: 3.3.1
    helm:
      values: |
        controllers:
          obsidian-couchdb:
            annotations:
              reloader.stakater.com/auto: "true"
            initContainers:
              init-config:
                image:
                  repository: public.ecr.aws/docker/library/busybox
                  tag: latest@sha256:9ae97d36d26566ff84e8893c64a6dc4fe8ca6d1144bf5b87b2b85a32def253c7
                  pullPolicy: IfNotPresent
                command:
                  - "/bin/sh"
                  - "-c"
                  - "cp /tmp/config/*.ini /opt/couchdb/etc/default.d/; ls -lrt /opt/couchdb/etc/default.d;"
            containers:
              main:
                image:
                  repository: public.ecr.aws/docker/library/couchdb
                  tag: 3.3.3
                envFrom:
                  - secretRef:
                      name: obsidian-couchdb-secret
                resources:
                  requests:
                    memory: 512Mi
                    cpu: 10m
                  limits:
                    memory: 1024Mi
        defaultPodOptions:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
        service:
          app:
            controller: obsidian-couchdb
            ports:
              http:
                port: 5984
        persistence:
            config:
              enabled: true
              type: configMap
              name: obsidian-couchdb-configmap
              advancedMounts:
                obsidian-couchdb:
                  init-config:
                    - path: /tmp/config
            data:
              enabled: true
              existingClaim: obsidian-couchdb
              advancedMounts:
                obsidian-couchdb:
                  app:
                    - path: /opt/couchdb/data
            config-storage:
              enabled: true
              type: emptyDir
              globalMounts:
                - path: /opt/couchdb/etc/default.d
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: obsidian-couchdb-configmap
  namespace: obsidian-livesync
data:
  couchdb.ini: |
    single_node = true
    max_document_size = 50000000

    [chttpd]
    require_valid_user = true
    bind_address = any
    max_http_request_size = 4294967296

    [httpd_auth]
    require_valid_user = true
    authentication_redirect = /_utils/session.html

    [httpd]
    WWW-Authenticate = Basic realm="couchdb"
    enable_cors = true

    [cors]
    origins = app://obsidian.md,capacitor://localhost,http://localhost
    credentials = true
    headers = accept, authorization, content-type, origin, referer
    methods = GET, PUT, POST, HEAD, DELETE
    max_age = 3600
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-couchdb
  namespace: obsidian-livesync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: obsidian-livesync
  namespace: obsidian-livesync
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: ingress-nginx-internal
  rules:
  - host: obsidian.<path:stringreplacesecret#domain>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: obsidian-couchdb
            port:
              number: 5984
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: obsidian-livesync
  namespace: obsidian-livesync
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  parentRefs:
  - name: internal
    namespace: gateway
    sectionName: https
  hostnames:
  - "obsidian.<path:stringreplacesecret#domain>"
  rules:
  - backendRefs:
    - name: obsidian-livesync
      port: 5984
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: obsidian-livesync
  namespace: obsidian-livesync
  annotations:
    external-dns.custom/type: private
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  endpoints:
    - dnsName: obsidian.<path:stringreplacesecret#domain>
      recordType: CNAME
      targets:
        - intgw.<path:stringreplacesecret#domain>
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"