---
kind: Namespace
apiVersion: v1
metadata:
  name: obsidian
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: obsidian
  labels:
    io.kompose.service: couchdb-claim0
  name: couchdb-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: obsidian
  labels:
    io.kompose.service: couchdb-claim1
  name: couchdb-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: obsidian
  annotations:
    kompose.cmd: kompose convert -f couchdb.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: couchdb
  name: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: couchdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f couchdb.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: couchdb
    spec:
      containers:
        - env:
            - name: COUCHDB_PASSWORD
              value: password
            - name: COUCHDB_USER
              value: admin
          image: couchdb:latest
          name: obsidian-livesync
          ports:
            - containerPort: 5984
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/couchdb/data
              name: couchdb-claim0
            - mountPath: /opt/couchdb/etc/local.ini
              name: couchdb-claim1
      restartPolicy: Always
      volumes:
        - name: couchdb-claim0
          persistentVolumeClaim:
            claimName: couchdb-claim0
        - name: couchdb-claim1
          persistentVolumeClaim:
            claimName: couchdb-claim1
---
apiVersion: v1
kind: Service
metadata:
  namespace: obsidian
  annotations:
    kompose.cmd: kompose convert -f couchdb.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: couchdb
  name: couchdb
spec:
  ports:
    - name: "5984"
      port: 5984
      targetPort: 5984
  selector:
    io.kompose.service: couchdb
