apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obsidian-couchdb
spec:
  destination:
    namespace: flux-system
  project: default
  sources:
  - git:
      repoURL: https://github.com/your-username/obsidian-couchdb.git
      revision: main
  target:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true

helmValues: |
  controllers.main.annotations.reloader.stakater.com/auto: "true"
  pod.securityContext.runAsUser: ${APP_UID}
  pod.securityContext.runAsGroup: ${APP_GID}
  pod.securityContext.fsGroup: ${APP_GID}
  pod.securityContext.fsGroupChangePolicy: "OnRootMismatch"

  containers.main.image.repository: public.ecr.aws/docker/library/couchdb
  containers.main.image.tag: 3.3.3
  env:
    COUCHDB_USER:
      value: admin
    COUCHDB_PASSWORD:
      value: password

  service.main.ports.http.port: &httpPort 5984

  ingress.main.enabled: true
  ingress.main.className: "internal"
  hosts:
    - host: *host
      paths:
        - path: /
          service:
            identifier: main
            port: *httpPort

  persistence.config.type: configMap
  persistence.config.name: obsidian-couchdb-configmap
  advancedMounts:
    main.init-config:
      - path: /tmp/config

  persistence.data.existingClaim: obsidian-data-pvc
  advancedMounts:
    main.main:
      - path: /opt/couchdb/data

  config-storage.type: emptyDir
  globalMounts:
    - path: /opt/couchdb/etc/default.d