---
kind: Namespace
apiVersion: v1
metadata:
  name: obsidian-livesync
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obsidian-livesync
  namespace: argocd
spec:
  destination:
    namespace: obsidian-livesync
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: app-template 
    repoURL: http://bjw-s.github.io/helm-charts/
    targetRevision: 3.3.1
    helm:
      values: |
        controllers:
          obsidian-couchdb:
            annotations:
              reloader.stakater.com/auto: "true"
            initContainers:
              init-config:
                image:
                  repository: public.ecr.aws/docker/library/busybox
                  tag: latest@sha256:9ae97d36d26566ff84e8893c64a6dc4fe8ca6d1144bf5b87b2b85a32def253c7
                  pullPolicy: IfNotPresent
                command:
                  - "/bin/sh"
                  - "-c"
                  - "cp /tmp/config/*.ini /opt/couchdb/etc/default.d/; ls -lrt /opt/couchdb/etc/default.d;"
            containers:
              main:
                image:
                  repository: public.ecr.aws/docker/library/couchdb
                  tag: 3.3.3
                envFrom:
                  - secretRef:
                      name: obsidian-couchdb-secret
                resources:
                  requests:
                    memory: 512Mi
                    cpu: 10m
                  limits:
                    memory: 1024Mi
        defaultPodOptions:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
        service:
          app:
            controller: obsidian-couchdb
            ports:
              http:
                port: 5984
        persistence:
            config:
              enabled: true
              type: configMap
              name: obsidian-couchdb-configmap
              advancedMounts:
                obsidian-couchdb:
                  init-config:
                    - path: /tmp/config
            data:
              enabled: true
              existingClaim: obsidian-couchdb
              advancedMounts:
                obsidian-couchdb:
                  app:
                    - path: /opt/couchdb/data
            config-storage:
              enabled: true
              type: emptyDir
              globalMounts:
                - path: /opt/couchdb/etc/default.d

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: obsidian-couchdb-configmap
data:
  couchdb.ini: |
    single_node = true
    max_document_size = 50000000

    [chttpd]
    require_valid_user = true
    bind_address = any
    max_http_request_size = 4294967296

    [httpd_auth]
    require_valid_user = true
    authentication_redirect = /_utils/session.html

    [httpd]
    WWW-Authenticate = Basic realm="couchdb"
    enable_cors = true

    [cors]
    origins = app://obsidian.md,capacitor://localhost,http://localhost
    credentials = true
    headers = accept, authorization, content-type, origin, referer
    methods = GET, PUT, POST, HEAD, DELETE
    max_age = 3600
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-couchdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi