apiVersion: apps/v1
kind: Deployment
metadata:
  name: obsidian-livesync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obsidian-livesync
  template:
    metadata:
      labels:
        app: obsidian-livesync
    spec:
      containers:
      - name: couchdb
        image: "apache/couchdb:latest"
        ports:
        - containerPort: 80
        env:
          - name: COUCHDB_USER
            value: admin
          - name: COUCHDB_PASSWORD
            value: password
        volumeMounts:
        - name: couchdb-data
          mountPath: /var/lib/couchdb
        configMap:
          name: couchdb-config
      volumes:
      - name: couchdb-data
        persistentVolumeClaim:
          claimName: couchdb-pvc

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-config
data:
  couchdb.config: |
    [couchdb]
    single_node = true
    uuid = obsidian-livesync

    [chttpd]
    bind_address = any
    require_valid_user = true

    [chttpd_auth]
    require_valid_user = true
    authentication_redirect = "/e=_/_utils/session.html"

    [httpd]
    WWW-Authenticate = 'Basic realm="couchdb"'
    enable_cors = true

    [cors]
    origins = app://obsidian.md,capacitor://localhost,http://localhost
    credentials = true
    headers = accept, authorization, content-type, origin, referer
    methods = GET, PUT, POST, HEAD, DELETE
    max_age = 3600

--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-livesync-couchdb-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
