kind: Namespace
apiVersion: v1
metadata:
  name: ollama
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
spec:
  project: default
  source:
    chart: app-template
    repoURL: http://bjw-s.github.io/helm-charts/
    targetRevision: 3.5.1
  helm:
    values: |
      replicaCount: 1
      knative:
        enabled: false
        containerConcurrency: 1
        timeoutSeconds: 300
        responseStartTimeoutSeconds: 300
        idleTimeoutSeconds: 300
      controllers:
        ollama:
          annotations:
            reloader.stakater.com/auto: "true"
          type: deployment
          strategy: Recreate
          containers:
            app:
              image:
                repository: ollama/ollama
                pullPolicy: IfNotPresent
                tag: "0.4.0"
              env:
                OLLAMA_MODELS: /models
                OLLAMA_DEBUG: 1
              pod:
                runtimeClassName: nvidia
                nodeSelector:
                  kubernetes.io/hostname: talos-03
          persistence:
            config:
              enabled: true
              existingClaim: ollama-pvc
            advancedMounts:
              ollama:
                app:
                  - path: /models
          service:
            app:
              controller: ollama
              type: LoadBalancer
              ports:
                http:
                  port: 11434
      destination:
        server: https://kubernetes.default.svc
        namespace: ollama
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ollama-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "400Gi"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pvc
spec:
  capacity:
    storage: "400Gi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /models
    nodeAffinity:
      required:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - talos-03