---
kind: Namespace
apiVersion: v1
metadata:
  name: ollama
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    chart: app-template
    repoURL: https://bjw-s-labs.github.io/helm-charts
    targetRevision: 4.1.2
    helm:
      values: |
        replicaCount: 1
        knative:
          enabled: false
          containerConcurrency: 1
          timeoutSeconds: 300
          responseStartTimeoutSeconds: 300
          idleTimeoutSeconds: 300
        controllers:
          ollama:
            annotations:
              reloader.stakater.com/auto: "true"
            type: deployment
            strategy: Recreate
            containers:
              app:
                image:
                  repository: ollama/ollama
                  pullPolicy: IfNotPresent
                  tag: "0.6.5"
                env:
                  OLLAMA_MODELS: /models
                  OLLAMA_DEBUG: 1
                  ENABLE_RAG_HYBRID_SEARCH: "true"
                  DATA_DIR: /models
            pod:
              runtimeClassName: nvidia
        persistence:
          config:
            enabled: true
            existingClaim: ollama-pvc
            advancedMounts:
              ollama: 
                app:
                  - path: /models
        service:
          app:
            controller: ollama
            type: LoadBalancer
            ports:
              http:
                port: 11434
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ollama-pvc
  namespace: ollama
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-nfs-csi"
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300G