---
kind: Namespace
apiVersion: v1
metadata:
  name: ollama
---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: ollama
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "-1"
# spec:
#   project: default
#   source:
#     repoURL: https://otwld.github.io/ollama-helm/
#     targetRevision: "0.64.0"
#     chart: ollama
#     helm:
#       values: |
#         replicaCount: 1
#         knative:
#           enabled: false
#           containerConcurrency: 1
#           timeoutSeconds: 300
#           responseStartTimeoutSeconds: 300
#           idleTimeoutSeconds: 300
#         image:
#           repository: ollama/ollama
#           pullPolicy: IfNotPresent
#           tag: "latest"  # Specify version or "latest"
#         imagePullSecrets: []
#         nameOverride: ""
#         fullnameOverride: ""
#         volumeMounts:
#           - name: ollama-volume
#             mountPath: /ollama
#         volumes:
#           - name: ollama-volume
#         persistentVolume:
#           enabled: true
#           existingClaim: ollama-pvc
#         runtimeClassName: "nvidia"
#         ollama:
#           models:
#             - llama3
#           insecure: false
#         service:
#           type: LoadBalancer
#           port: 11434
#         nodeSelector:
#           kubernetes.io/hostname: talos-03
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: ollama
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    chart: app-template
    repoURL: http://bjw-s.github.io/helm-charts/
    targetRevision: 3.5.1
    helm:
      values: |
        replicaCount: 1
        knative:
          enabled: false
          containerConcurrency: 1
          timeoutSeconds: 300
          responseStartTimeoutSeconds: 300
          idleTimeoutSeconds: 300
        controllers:
          ollama:
            annotations:
              reloader.stakater.com/auto: "true"
            type: deployment
            strategy: Recreate
            containers:
              app:
                image:
                  repository: ollama/ollama
                  pullPolicy: IfNotPresent
                  tag: "0.4.0"
                runtimeClassName: "nvidia"
        imagePullSecrets: []
        nameOverride: ""
        fullnameOverride: ""
        volumeMounts:
          - name: ollama-volume
            mountPath: /ollama
        volumes:
          - name: ollama-volume
        persistentVolume:
          enabled: true
          existingClaim: ollama-pvc
        runtimeClassName: "nvidia"
        ollama:
          models:
            - llama3
          insecure: false
        service:
          app:
            controller: ollama
            type: LoadBalancer
            ports:
              http:
                port: 11434
          # nodeSelector:
          #   kubernetes.io/hostname: talos-03
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ollama-pvc
  namespace: ollama
  labels:
    app.kubernetes.io/name: ollama
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100G