---
kind: Namespace
apiVersion: v1
metadata:
  name: ollama
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://otwld.github.io/ollama-helm/
    targetRevision: "0.33.0"  # Assuming this matches the chart version or tag
    chart: ollama
    helm:
      values: |
        replicaCount: 1

        knative:
          enabled: false
          containerConcurrency: 0
          timeoutSeconds: 300
          responseStartTimeoutSeconds: 300
          idleTimeoutSeconds: 300

        image:
          repository: ollama/ollama
          pullPolicy: IfNotPresent
          tag: ""

        imagePullSecrets: []

        nameOverride: ""
        fullnameOverride: ""

        ollama:
          gpu:
            enabled: true
            type: 'nvidia'
            number: 1
          models:
            - llama3
          insecure: false

        serviceAccount:
          create: true
          automount: true
          annotations: {}
          name: ""

        podAnnotations: {}
        podLabels: {}

        podSecurityContext: {}
        securityContext: {}

        runtimeClassName: ""

        service:
          type: ClusterIP
          port: 11434
          nodePort: 31434
          annotations: {}
  nodeSelector:
        nvidia-gpu: "true"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ollama-pvc
  namespace: ollama
  labels:
    app.kubernetes.io/name: ollama
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100G

        

