---
kind: Namespace
apiVersion: v1
metadata:
  name: outline
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline-configsecrets
  namespace: outline
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: postgrespassword
      remoteRef:
        key: postgres.cluster01.outline.owner
        property: password
    - secretKey: postgresuser
      remoteRef:
        key: postgres.cluster01.outline.owner
        property: username

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-data-pvc
  namespace: outline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data-pvc
  namespace: outline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: outline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: https-portal-data-pvc
  namespace: outline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: outline-deployment
  namespace: outline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outline
  template:
    metadata:
      labels:
        app: outline
    spec:
      containers:
      - name: outline
        image: docker.getoutline.com/outlinewiki/outline:latest
        env:
          - name: DATABASE_URL
            value: postgres://user:pass@cluster01.postgres:5432/outline
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: postgresuser
                name: outline-configsecrets
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgrespassword
                name: outline-configsecrets      
          - name: POSTGRES_DB
            value: 'outline'
        ports:
          - containerPort: 3000
        volumeMounts:
          - name: storage-data-pvc
            mountPath: /var/lib/outline/data

      - name: postgres
        image: postgres
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: postgresuser
                name: outline-configsecrets
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgrespassword
                name: outline-configsecrets      
          - name: POSTGRES_DB
            value: 'outline'
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: database-data-pvc
            mountPath: /var/lib/postgresql/data

      - name: redis
        image: redis:alpine
        ports:
          - containerPort: 6379
        volumeMounts:
          - name: redis-data-pvc
            mountPath: /data

      - name: https-portal
        image: docker.getoutline.com/outlinewiki/https-portal:latest
        env:
          - name: POSTGRES_URL
            value: postgres://user:pass@cluster01.postgres:5432/outline
          - name: REDIS_HOST
            value: redis
        ports:
          - containerPort: 3001
        volumeMounts:
          - name: https-portal-data-pvc
            mountPath: /var/lib/https-portal/data

      - name: node-app
        image: docker.getoutline.com/outlinewiki/node-app:latest
        env:
          - name: POSTGRES_URL
            value: postgres://user:pass@cluster01.postgres:5432/outline
          - name: REDIS_HOST
            value: redis
          - name: HTTPS_PORTAL_URL
            value: https://https-portal:3001
        ports:
          - containerPort: 80