---
kind: Namespace
apiVersion: v1
metadata:
  name: outline
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: https-portal-data-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: https-portal-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: outline-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outline
  template:
    metadata:
      labels:
        app: outline
    spec:
      containers:
      - name: outline
        image: docker.getoutline.com/outlinewiki/outline:latest
        env:
          - name: DATABASE_URL
            value: postgres://user:pass@cluster01.postgres:5432/outline
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: postgresuser
                name: outline-configsecrets
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgrespassword
                name: outline-configsecrets      
          - name: POSTGRES_DB
            value: 'outline'
        ports:
          - containerPort: 3000
        volumeMounts:
          - name: database-data-pvc
            mountPath: /var/lib/outline/data

      - name: redis
        image: redis:alpine
        ports:
          - containerPort: 6379
        volumeMounts:
          - name: redis-data-pv
            mountPath: /data

      - name: https-portal
        image: docker.getoutline.com/outlinewiki/https-portal:latest
        env:
          - name: POSTGRES_URL
            value: postgres://user:pass@cluster01.postgres:5432/outline
          - name: REDIS_HOST
            value: redis
        ports:
          - containerPort: 3001
        volumeMounts:
          - name: https-portal-data-pv
            mountPath: /var/lib/https-portal/data

      - name: node-app
        image: docker.getoutline.com/outlinewiki/node-app:latest
        env:
          - name: POSTGRES_URL
            value: postgres://user:pass@cluster01.postgres:5432/outline
          - name: REDIS_HOST
            value: redis
          - name: HTTPS_PORTAL_URL
            value: https://https-portal:3001
        ports:
          - containerPort: 80