apiVersion: v1
kind: Secret
metadata:
  namespace: authentik
  labels:
    app.kubernetes.io/instance: mtsoutpost
    app.kubernetes.io/managed-by: goauthentik.io
    app.kubernetes.io/name: authentik-proxy
    app.kubernetes.io/version: 2021.12.3
  name: authentik-outpost-api
stringData:
  authentik_host_insecure: "true"
type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
  namespace: authentik
  labels:
    app.kubernetes.io/part-of: homepage
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_VAR_TOKEN: "{{ .token }}"
        AUTHENTIK_VAR_HOST: "{{ .host }}"
  data:
    - secretKey: token
      remoteRef:
        key: authentik
        property: auth_token
    - secretKey: host
      remoteRef: 
        key: authentik
      property: authentik_host
---
apiVersion: v1
kind: Service
metadata:
  namespace: authentik
  labels:
    app.kubernetes.io/instance: mtsoutpost
    app.kubernetes.io/managed-by: goauthentik.io
    app.kubernetes.io/name: authentik-proxy
    app.kubernetes.io/version: 2021.12.3
  name: authentik-outpost
spec:
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: http
    - name: https
      port: 9443
      protocol: TCP
      targetPort: https
  type: LoadBalancer
  selector:
    app.kubernetes.io/managed-by: goauthentik.io
    app.kubernetes.io/name: authentik-outpost
    app.kubernetes.io/instance: mtsoutpost
---
apiVersion: apps/v1
kind: Deployment
namespace: authentik
metadata:
  labels:
    app.kubernetes.io/instance: mtsoutpost
    app.kubernetes.io/managed-by: goauthentik.io
    app.kubernetes.io/name: authentik-proxy
    app.kubernetes.io/version: 2021.12.3
  name: authentik-outpost
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: mtsoutpost
      app.kubernetes.io/managed-by: goauthentik.io
      app.kubernetes.io/name: authentik-proxy
      app.kubernetes.io/version: 2021.12.3
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mtsoutpost
        app.kubernetes.io/managed-by: goauthentik.io
        app.kubernetes.io/name: authentik-proxy
        app.kubernetes.io/version: 2021.12.3
    spec:
      containers:
        - env:
          - name: AUTHENTIK_HOST
            valueFrom:
              secretKeyRef:
                key: authentik
                name: authentik_host
          - name: AUTHENTIK_TOKEN
            valueFrom:
              secretKeyRef:
                key: authentik
                name: auth_token
          - name: AUTHENTIK_INSECURE
            valueFrom:
              secretKeyRef:
                key: authentik_host_insecure
                name: authentik-outpost-api
        image: ghcr.io/goauthentik/proxy
        name: proxy
        ports:
          - containerPort: 9000
            name: http
            protocol: TCP
          - containerPort: 9443
            name: https
            protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
namespace: authentik
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    traefik.ingress.kubernetes.io/affinity: "true"
  labels:
    app.kubernetes.io/instance: mtsoutpost
    app.kubernetes.io/managed-by: goauthentik.io
    app.kubernetes.io/name: authentik-proxy
    app.kubernetes.io/version: 2021.12.3
  name: authentik-outpost
spec:
  rules:
  - host: https://auth.marcthespot.com
    http:
      paths:
      - backend:
          service:
            name: authentik-outpost
            port:
              name: http
        path: /