
---
kind: Namespace
apiVersion: v1
metadata:
  name: qbittorrent
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent
  namespace: qbittorrent
  labels:
    app.kubernetes.io/part-of: qbittorrent
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        QBIT_VAR_VPN_USERNAME:  "{{ .vpn_user }}"
        QBIT_VAR_VPN_PASSWORD:  "{{ .vpn_pass }}"
  data:
    - secretKey: vpn_user
      remoteRef:
        key: qbittorrent
        property: OPENVPN_USERNAME
    - secretKey: vpn_pass
      remoteRef:
        key: qbittorrent
        property: OPENVPN_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  type: ClusterIP
  selector:
    app: qbittorrent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorent
  namespace: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      enableServiceLinks: true
      serviceAccountName: default
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 1000
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "100"
          volumeMounts:
            - mountPath: /config
              name: qbittorrent-config
              subPath: qbittorrent/config
            - mountPath: /data
              name: qbittorrent-data
        - name: gluten
          image: qmcgaw/gluetun:latest
          env:
          - name: VPN_SERVICE_PROVIDER
            value: "expressvpn"
          - name: FIREWALL_OUTBOUND_SUBNETS
            value: "192.168.1.0/24"
          - name: OPENVPN_USER
            value: "{{ .vpn_user }}"
          - name: OPENVPN_PASSWORD
            value: "{{ .vpn_user }}"
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /config
              name: qbittorrent-config
              subPath: gluetun/config
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: qbittorrent-data
          persistentVolumeClaim:
            claimName: qbittorrent-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: qbittorrent
  name: qbittorrent-config
  namespace: qbittorrent
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
--- 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbittorrent-data
  namespace: qbittorrent
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-nfs-csi"
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent
  namespace: qbittorrent
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: ingress-nginx-internal
  rules:
  - host: qb.<path:stringreplacesecret#domain>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qbittorrent
            port:
              number: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qbittorrent
  namespace: qbittorrent
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  parentRefs:
  - name: internal
    namespace: gateway
    sectionName: https
  hostnames:
  - "qb.<path:stringreplacesecret#domain>"
  rules:
  - backendRefs:
    - name: qbittorent
      port: 80
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: qbittorrent
  namespace: qbittorrent
  annotations:
    external-dns.custom/type: private
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  endpoints:
    - dnsName: qb.<path:stringreplacesecret#domain>
      recordType: CNAME
      targets:
        - intgw.<path:stringreplacesecret#domain>
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"