---
apiVersion: v1
kind: Deployment
metadata:
  name: hbbr
  labels:
    app: hbr
spec:
  selector: hbbr
  template:
    spec:
      containers:
        - name: hbbr
          image: rustdesk/rustdesk-server:latest
          command: [hbbr]
          volumeMounts:
            - name: data
              mountPath: /root
              sourcePath: ./data
          restartPolicy: unless-stopped
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hbbr
  labels:
    app: hbr
spec:
  selector: hbbr
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: 3001
---

apiVersion: v1
kind: Deployment
metadata:
  name: hbbs
  labels:
    app: hbbs
spec:
  selector: hbbs
  template:
    spec:
      containers:
        - name: hbbs
          image: rustdesk/rustdesk-server:latest
          command: [hbbs]
          volumeMounts:
            - name: data
              mountPath: /root
              sourcePath: ./data
          restartPolicy: unless-stopped
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hbbs
  labels:
    app: hbbs
spec:
  selector: hbbs
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
