---
kind: Namespace
apiVersion: v1
metadata:
  name: searchxng
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: searchxng
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    chart: app-template
    repoURL: http://bjw-s.github.io/helm-charts/
    targetRevision: 3.5.1
    helm:
      values: |
        controllers:
          searxng:
            annotations:
              reloader.stakater.com/auto: "true"
            containers:
              searchxng:
                image:
                  repository: docker.io/searxng/searxng
                  tag: 2024.6.30-39aaac40d@sha256:149477f50e9fd7a90bd1455009b332433d65a9beeb0e0a6f9a4bdc11a860c0b6
                env:
                  TZ: America/New_York
                  SEARXNG_BASE_URL: https://search.<path:stringreplacesecret#domain>
                  SEARXNG_URL: https://search.<path:stringreplacesecret#domain>
                  SEARXNG_PORT: 8080
                # envFrom:
                #   - secretRef:
                #       name: searxng-secret
                probes:
                  liveness: &probes
                    enabled: true
                    custom: true
                    spec:
                      httpGet:
                        path: /stats
                        port: 8080
                      initialDelaySeconds: 0
                      periodSeconds: 10
                      timeoutSeconds: 1
                      failureThreshold: 3
                  readiness: *probes
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities:
                    add: ["CHOWN", "SETGID" ,"SETUID", "DAC_OVERRIDE"]
                    drop: ["ALL"]
                resources:
                  requests:
                    cpu: 10m
                    memory: 256Mi
                  limits:
                    memory: 2000Mi
        service:
            app:
              controller: searxng
              ports:
                http:
                  port: 8080
        persistence:
            config:
              enabled: true
              existingClaim: searchxng-configmap
              advancedMounts:
                searchxng:
                  app:
                    - path: /etc/searxng/settings.yml
                    - path: /etc/searxng/limiter.toml
  destination:
    server: https://kubernetes.default.svc
    namespace: searchxng
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: searchxng
  name: searchxng-configmap
  namespace: searchxng
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi