---
kind: Namespace
apiVersion: v1
metadata:
  name: searchxng
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: searcgxng
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    chart: app-template
    repoURL: http://bjw-s.github.io/helm-charts/
    targetRevision: 3.5.1
    helm:
      values: |
      controllers:
      app:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: searxng/searxng
              tag: 2024.11.10-dfaf5868e
            env:
              BASE_URL: https://search.marcthespot.com
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /stats
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETGID
                  - SETUID
                  - DAC_OVERRIDE
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 3Gi
      defaultPodOptions:
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: *app
      service:
        app:
          controller: app
          ports:
            http:
              port: *port
      persistence:
        config:
          type: configMap
          name: searxng-configmap
          advancedMounts:
            app:
              app:
                - path: /etc/searxng/settings.yml
                  subPath: settings.yml
                  readOnly: true
                - path: /etc/searxng/limiter.toml
                  subPath: limiter.toml
                  readOnly: true
        tmp:
          type: emptyDir
          advancedMounts:
            app:
              app:
                - path: /etc/searxng
                - path: /tmp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: searchxng-ingress
  namespace: searchxng
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: ingress-nginx-internal
  rules:
  - host: search.<path:stringreplacesecret#domain>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: searchxng
            port:
              number: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: searchxng-http
  namespace: searchxng
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  parentRefs:
  - name: internal
    namespace: gateway
    sectionName: https
  hostnames:
  - "search.<path:stringreplacesecret#domain>"
  rules:
  - backendRefs:
    - name: searchxng
      port: 8080
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: searchxng
  namespace: searchxng
  annotations:
    external-dns.custom/type: private
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  endpoints:
    - dnsName: search.<path:stringreplacesecret#domain>
      recordType: CNAME
      targets:
        - intgw.<path:stringreplacesecret#domain>
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"