---
kind: Namespace
apiVersion: v1
metadata:
  name: searxng
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: searxng
  namespace: searxng
automountServiceAccountToken: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-settings
  namespace: searxng
data:
  settings.yml: |
    use_default_settings: true
    
    server:
      secret_key: "57dc63125e7eef404481411b99c21fb9a5763b724b0bc88f2440ef373cf94809"
      limiter: false
      image_proxy: true
      port: 8080
      bind_address: "0.0.0.0"
    
    ui:
      static_use_hash: true
    
    search:
      safe_search: 0
      autocomplete: ""
      default_lang: ""
      formats:
        - html
        - json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-limiter
  namespace: searxng
data:
  limiter.toml: |
    [botdetection.ip_limit]
    # activate link_token method in the ip_limit method
    link_token = true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-uwsgi
  namespace: searxng
data:
  uwsgi.ini: |
    [uwsgi]
    # Who will run the code
    uid = searxng
    gid = searxng
    
    # Number of workers (usually CPU count)
    # default value: %k (= number of CPU core, see Dockerfile)
    workers = %k
    
    # Number of threads per worker
    # default value: 4 (see Dockerfile)
    threads = 4
    
    # The right granted on the created socket
    chmod-socket = 666
    
    # Plugin to use and interpreter config
    single-interpreter = true
    master = true
    plugin = python3
    lazy-apps = true
    enable-threads = 4
    
    # Module to import
    module = searx.webapp
    
    # Virtualenv and python path
    pythonpath = /usr/local/searxng/
    chdir = /usr/local/searxng/searx/
    
    # automatically set processes name to something meaningful
    auto-procname = true
    
    # Disable request logging for privacy
    disable-logging = true
    log-5xx = true
    
    # Set the max size of a request (request-body excluded)
    buffer-size = 8192
    
    # No keep alive
    # See https://github.com/searx/searx-docker/issues/24
    add-header = Connection: close
    
    # uwsgi serves the static files
    static-map = /static=/usr/local/searxng/searx/static
    # expires set to one day
    static-expires = /* 86400
    static-gzip-all = True
    offload-threads = 4
---
apiVersion: v1
kind: Service
metadata:
  name: searxng
  namespace: searxng
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  namespace: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "searxng"
  template:
    spec:
      serviceAccountName: searxng
      securityContext:
        {}
      containers:
        - name: searxng
          securityContext:
            {}
          image: "searxng/searxng:latest"
          imagePullPolicy: 
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
          volumeMounts:
            - mountPath: /etc/searxng/settings.yml
              name: searxng-settings
              subPath: settings.yml
              readOnly: true
            - mountPath: /etc/searxng/limiter.toml
              name: searxng-limiter
              subPath: limiter.toml
              readOnly: true
            - mountPath: /etc/searxng/uwsgi.ini
              name: searxng-uwsgi
              subPath: uwsgi.ini
              readOnly: true
      volumes:
        - name: searxng-settings
          configMap:
            name: searxng-settings
        - name: searxng-limiter
          configMap:
            name: searxng-limiter
        - name: searxng-uwsgi
          configMap:
            name: searxng-uwsgi
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   labels:
#     app: searxng
#   name: searxng-configmap
#   namespace: searxng
# spec:
#   accessModes: ["ReadWriteOnce"]
#   resources:
#     requests:
#       storage: 2Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: searxng-ingress
  namespace: searxng
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: ingress-nginx-internal
  rules:
  - host: search.<path:stringreplacesecret#domain>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: searxng
            port:
              number: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: searxng-http
  namespace: searxng
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  parentRefs:
  - name: internal
    namespace: gateway
    sectionName: https
  hostnames:
  - "search.<path:stringreplacesecret#domain>"
  rules:
  - backendRefs:
    - name: searxng
      port: 8080
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: searxng
  namespace: searxng
  annotations:
    external-dns.custom/type: private
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  endpoints:
    - dnsName: search.<path:stringreplacesecret#domain>
      recordType: CNAME
      targets:
        - intgw.<path:stringreplacesecret#domain>
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"