---
kind: Namespace
apiVersion: v1
metadata:
  name: siyuan

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: siyuan-workspace-pvc

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: main

spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main
        image: b3log/siyuan
        command: ["--accessAuthCode=password"]

---

apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  selector:
    app: main
  ports:
  - protocol: TCP
    port: 6806
    targetPort: 6806
  type: ClusterIP