apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: standardnotes/server
        env_file: .env
        ports:
          - containerPort: 3000
          - containerPort: 3125
        volumeMounts:
        - name: logs
          mountPath: /var/lib/server/logs
        - name: uploads
          mountPath: /opt/server/packages/files/dist/uploads
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: server-logs-pvc
      - name: uploads
        persistentVolumeClaim:
          claimName: server-uploads-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack:3.5
        ports:
          - containerPort: 4566
        environment:
          - name: SERVICES
            value: sns,sqs
          - name: HOSTNAME_EXTERNAL
            value: localstack
          - name: LS_LOG
            value: warn
        volumeMounts:
        - name: bootstrap-script
          mountPath: /etc/localstack/init/ready.d/
      volumes:
      - name: bootstrap-script
        configMap:
          name: localstack-bootstrap-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mysql:8
        ports:
          - containerPort: 3306
        environment:
          - name: MYSQL_DATABASE
            value: standard_notes_db
          - name: MYSQL_USER
            value: std_notes_user
          - name: MYSQL_ROOT_PASSWORD
            value: changeme123
          - name: MYSQL_PASSWORD
            value: changeme123
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: import-script
          mountPath: /docker-entrypoint-initdb.d

      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: db-data-pvc
      - name: import-script
        configMap:
          name: db-import-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache
        image: redis:6.2-alpine
        ports:
          - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data

      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: cache-data-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
