apiVersion: apps/v1
kind: Deployment
metadata:
  name: standardnotes-self-hosted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: standardnotes-self-hosted
  template:
    metadata:
      labels:
        app: standardnotes-self-hosted
    spec:
      containers:
      - name: self-hosted
        image: <your-image-name>
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: db-import-config
data:
  docker-entrypoint-initdb.d: |
    # Your custom import script here

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack-self-hosted
        image: localstack/localstack:3.0
        expose:
          - port: 4566
        restartPolicy: Always
        volumeMounts:
        - name: localstack-bootstrap
          mountPath: /etc/localstack/init/ready.d/
      volumes:
      - name: localstack-bootstrap
        configMap:
          name: localstack-bootstrap-config

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db-self-hosted
        image: docker.io/bitnami/mysql:8.4.1-debian-12-r3
        env:
          - name: MYSQL_DATABASE
            value: standard_notes_db
          - name: MYSQL_USER
            value: std_notes_user
          - name: MYSQL_ROOT_PASSWORD
            value: changeme123
          - name: MYSQL_PASSWORD
            value: changeme123
          - name: DB_HOST
            value: localhost
        expose:
          - port: 3306
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql

      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache-self-hosted
        image: redis:6.0-alpine
        volumeMounts:
        - name: cache-data
          mountPath: /data
      volumes:
      - name: cache-data
        persistentVolumeClaim:
          claimName: cache-data-pvc

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: standardnotes-self-hosted
spec:
  podSelector:
    matchLabels:
      app: standardnotes-self-hosted
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: standardnotes-self-hosted